import path from "node:path";
import fs from "node:fs";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ---------------------------------------------------------------------------
// Global env loader: walk up from the current workspace directory until we
// find the repo-root `.env.local` and load it into `process.env`.
//
// This makes the root `.env.local` automatically available to ALL workspaces
// (core, gutter, ohd, etc.) without requiring duplicate `.env.local` files
// in each module directory.
//
// For Vercel deployments, env vars should still be configured in the Vercel
// dashboard per-project. This loader only affects local development.
// ---------------------------------------------------------------------------
function loadRootEnvLocal() {
  let dir = __dirname;
  while (dir !== path.dirname(dir)) {
    const candidate = path.join(dir, ".env.local");
    if (fs.existsSync(candidate)) {
      const content = fs.readFileSync(candidate, "utf-8");
      content.split("\n").forEach((line) => {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) return;
        const eqIndex = trimmed.indexOf("=");
        if (eqIndex === -1) return;
        const key = trimmed.slice(0, eqIndex).trim();
        let value = trimmed.slice(eqIndex + 1).trim();
        if (
          (value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))
        ) {
          value = value.slice(1, -1);
        }
        if (key && !(key in process.env)) {
          process.env[key] = value;
        }
      });
      return;
    }
    dir = path.dirname(dir);
  }
}

loadRootEnvLocal();

// Auto-generated by generate-routes.js from module definitions
const rewritesPath = path.join(__dirname, "src", "app", "rewrites.json");
const autoRewrites = fs.existsSync(rewritesPath)
  ? JSON.parse(fs.readFileSync(rewritesPath, "utf-8"))
  : [];

/** @type {import('next').NextConfig} */
const nextConfig = {
  turbopack: {
    root: __dirname,
  },
  onDemandEntries: {
    // Keep dev pages hot longer to avoid tab-switch recompiles that feel like reloads.
    maxInactiveAge: 60 * 60 * 1000,
    // Raised from 8 → 100: App Router generates multiple webpack entries per route,
    // so 8 was exhausted quickly when 10+ tabs are open across different routes.
    pagesBufferLength: 100,
  },
  webpack(config, { dev }) {
    if (dev) {
      // Narrow the watcher to source files only; excludes directories that get
      // incidental writes (Supabase temp files, git index, OS metadata) that
      // would otherwise trigger spurious Fast Refresh rebuilds on Windows.
      config.watchOptions = {
        ...config.watchOptions,
        ignored: [
          '**/node_modules/**',
          '**/.git/**',
          '**/.next/**',
          '**/supabase/.temp/**',
          '**/supabase/db/**',
        ],
      };
    }
    return config;
  },
  async rewrites() {
    return autoRewrites;
  },
};

export default nextConfig;
