/**
 * Centralized icon registry — maps string names to Font Awesome icon
 * definitions.
 *
 * Every icon used anywhere in the app should be registered here so that
 * string-based icon references (stored in the database, action configs, etc.)
 * resolve to the correct Font Awesome icon.
 *
 * ─────────────────────────────────────────────────────────────────────
 * COVERAGE: This file includes every icon in the free Font Awesome
 * "solid" set (1422 icons, the default/filled style used by bare
 * kebab-case keys, e.g. "trash", "pen", "house") AND every icon in the
 * free "regular"/outline set (169 icons, reachable via a
 * "-outline" suffix, e.g. "trash-outline", "circle-check-outline").
 *
 * Free Font Awesome "brands" icons (company/product logos) are
 * intentionally NOT included here — they're a different use case
 * (representing a specific third-party brand, not a generic UI action
 * or concept), and mixing them into a general-purpose UI icon registry
 * risks accidental trademark/logo misuse in unrelated contexts. If a
 * brand icon is genuinely needed somewhere (e.g. "sign in with
 * Google"), import it directly at the call site instead of adding it
 * here.
 *
 * ⚠️ BUNDLE SIZE WARNING: This file statically imports every icon in
 * both free sets (~1591 icon definitions total). Since this is a
 * static/eager import list, ALL of them are included in the client
 * JavaScript bundle wherever this file is imported — Font Awesome's
 * icon objects are fairly small individually, but at this scale it adds
 * real weight (expect on the order of low-single-digit MB before
 * gzip/minification). This is a deliberate trade-off for having "every
 * icon available by name" (e.g. for database-driven icon selection),
 * not an oversight. If bundle size becomes a measured problem later,
 * the fix is to switch resolveIcon() to a dynamic import per icon
 * (e.g. via a generated lookup of import() calls) instead of one
 * static ICON_MAP — that is a bigger refactor and intentionally NOT
 * done here, since it changes resolveIcon() from synchronous to
 * asynchronous and would require updating every call site.
 * ─────────────────────────────────────────────────────────────────────
 */

import {
  fa0,
  fa1,
  fa2,
  fa3,
  fa4,
  fa5,
  fa6,
  fa7,
  fa8,
  fa9,
  faA,
  faAddressBook,
  faAddressCard,
  faAlarmClock,
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faAnchor,
  faAnchorCircleCheck,
  faAnchorCircleExclamation,
  faAnchorCircleXmark,
  faAnchorLock,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAnglesDown,
  faAnglesLeft,
  faAnglesRight,
  faAnglesUp,
  faAnkh,
  faAppleWhole,
  faAquarius,
  faArchway,
  faAries,
  faArrowDown,
  faArrowDown19,
  faArrowDown91,
  faArrowDownAZ,
  faArrowDownLong,
  faArrowDownShortWide,
  faArrowDownUpAcrossLine,
  faArrowDownUpLock,
  faArrowDownWideShort,
  faArrowDownZA,
  faArrowLeft,
  faArrowLeftLong,
  faArrowPointer,
  faArrowRight,
  faArrowRightArrowLeft,
  faArrowRightFromBracket,
  faArrowRightLong,
  faArrowRightToBracket,
  faArrowRightToCity,
  faArrowRotateLeft,
  faArrowRotateRight,
  faArrowTrendDown,
  faArrowTrendUp,
  faArrowTurnDown,
  faArrowTurnUp,
  faArrowUp,
  faArrowUp19,
  faArrowUp91,
  faArrowUpAZ,
  faArrowUpFromBracket,
  faArrowUpFromGroundWater,
  faArrowUpFromWaterPump,
  faArrowUpLong,
  faArrowUpRightDots,
  faArrowUpRightFromSquare,
  faArrowUpShortWide,
  faArrowUpWideShort,
  faArrowUpZA,
  faArrowsDownToLine,
  faArrowsDownToPeople,
  faArrowsLeftRight,
  faArrowsLeftRightToLine,
  faArrowsRotate,
  faArrowsSpin,
  faArrowsSplitUpAndLeft,
  faArrowsToCircle,
  faArrowsToDot,
  faArrowsToEye,
  faArrowsTurnRight,
  faArrowsTurnToDots,
  faArrowsUpDown,
  faArrowsUpDownLeftRight,
  faArrowsUpToLine,
  faAsterisk,
  faAt,
  faAtom,
  faAudioDescription,
  faAustralSign,
  faAward,
  faB,
  faBaby,
  faBabyCarriage,
  faBackward,
  faBackwardFast,
  faBackwardStep,
  faBacon,
  faBacteria,
  faBacterium,
  faBagShopping,
  faBahai,
  faBahtSign,
  faBan,
  faBanSmoking,
  faBandage,
  faBangladeshiTakaSign,
  faBarcode,
  faBars,
  faBarsProgress,
  faBarsStaggered,
  faBaseball,
  faBaseballBatBall,
  faBasketShopping,
  faBasketball,
  faBath,
  faBatteryEmpty,
  faBatteryFull,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryThreeQuarters,
  faBed,
  faBedPulse,
  faBeerMugEmpty,
  faBell,
  faBellConcierge,
  faBellSlash,
  faBezierCurve,
  faBicycle,
  faBinoculars,
  faBiohazard,
  faBitcoinSign,
  faBlender,
  faBlenderPhone,
  faBlog,
  faBold,
  faBolt,
  faBoltLightning,
  faBomb,
  faBone,
  faBong,
  faBook,
  faBookAtlas,
  faBookBible,
  faBookBookmark,
  faBookJournalWhills,
  faBookMedical,
  faBookOpen,
  faBookOpenReader,
  faBookQuran,
  faBookSkull,
  faBookTanakh,
  faBookmark,
  faBorderAll,
  faBorderNone,
  faBorderTopLeft,
  faBoreHole,
  faBottleDroplet,
  faBottleWater,
  faBowlFood,
  faBowlRice,
  faBowlingBall,
  faBox,
  faBoxArchive,
  faBoxOpen,
  faBoxTissue,
  faBoxesPacking,
  faBoxesStacked,
  faBraille,
  faBrain,
  faBrazilianRealSign,
  faBreadSlice,
  faBridge,
  faBridgeCircleCheck,
  faBridgeCircleExclamation,
  faBridgeCircleXmark,
  faBridgeLock,
  faBridgeWater,
  faBriefcase,
  faBriefcaseMedical,
  faBroom,
  faBroomBall,
  faBrush,
  faBucket,
  faBug,
  faBugSlash,
  faBugs,
  faBuilding,
  faBuildingCircleArrowRight,
  faBuildingCircleCheck,
  faBuildingCircleExclamation,
  faBuildingCircleXmark,
  faBuildingColumns,
  faBuildingFlag,
  faBuildingLock,
  faBuildingNgo,
  faBuildingShield,
  faBuildingUn,
  faBuildingUser,
  faBuildingWheat,
  faBullhorn,
  faBullseye,
  faBurger,
  faBurst,
  faBus,
  faBusSide,
  faBusSimple,
  faBusinessTime,
  faC,
  faCableCar,
  faCakeCandles,
  faCalculator,
  faCalendar,
  faCalendarCheck,
  faCalendarDay,
  faCalendarDays,
  faCalendarMinus,
  faCalendarPlus,
  faCalendarWeek,
  faCalendarXmark,
  faCamera,
  faCameraRetro,
  faCameraRotate,
  faCampground,
  faCancer,
  faCandyCane,
  faCannabis,
  faCapricorn,
  faCapsules,
  faCar,
  faCarBattery,
  faCarBurst,
  faCarOn,
  faCarRear,
  faCarSide,
  faCarTunnel,
  faCaravan,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretUp,
  faCarrot,
  faCartArrowDown,
  faCartFlatbed,
  faCartFlatbedSuitcase,
  faCartPlus,
  faCartShopping,
  faCashRegister,
  faCat,
  faCediSign,
  faCentSign,
  faCertificate,
  faChair,
  faChalkboard,
  faChalkboardUser,
  faChampagneGlasses,
  faChargingStation,
  faChartArea,
  faChartBar,
  faChartColumn,
  faChartDiagram,
  faChartGantt,
  faChartLine,
  faChartPie,
  faChartSimple,
  faCheck,
  faCheckDouble,
  faCheckToSlot,
  faCheese,
  faChess,
  faChessBishop,
  faChessBoard,
  faChessKing,
  faChessKnight,
  faChessPawn,
  faChessQueen,
  faChessRook,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faChildCombatant,
  faChildDress,
  faChildReaching,
  faChildren,
  faChurch,
  faCircle,
  faCircleArrowDown,
  faCircleArrowLeft,
  faCircleArrowRight,
  faCircleArrowUp,
  faCircleCheck,
  faCircleChevronDown,
  faCircleChevronLeft,
  faCircleChevronRight,
  faCircleChevronUp,
  faCircleDollarToSlot,
  faCircleDot,
  faCircleDown,
  faCircleExclamation,
  faCircleH,
  faCircleHalfStroke,
  faCircleInfo,
  faCircleLeft,
  faCircleMinus,
  faCircleNodes,
  faCircleNotch,
  faCirclePause,
  faCirclePlay,
  faCirclePlus,
  faCircleQuestion,
  faCircleRadiation,
  faCircleRight,
  faCircleStop,
  faCircleUp,
  faCircleUser,
  faCircleXmark,
  faCity,
  faClapperboard,
  faClipboard,
  faClipboardCheck,
  faClipboardList,
  faClipboardQuestion,
  faClipboardUser,
  faClock,
  faClockRotateLeft,
  faClone,
  faClosedCaptioning,
  faClosedCaptioningSlash,
  faCloud,
  faCloudArrowDown,
  faCloudArrowUp,
  faCloudBolt,
  faCloudMeatball,
  faCloudMoon,
  faCloudMoonRain,
  faCloudRain,
  faCloudShowersHeavy,
  faCloudShowersWater,
  faCloudSun,
  faCloudSunRain,
  faClover,
  faCode,
  faCodeBranch,
  faCodeCommit,
  faCodeCompare,
  faCodeFork,
  faCodeMerge,
  faCodePullRequest,
  faCoins,
  faColonSign,
  faComment,
  faCommentDollar,
  faCommentDots,
  faCommentMedical,
  faCommentNodes,
  faCommentSlash,
  faCommentSms,
  faComments,
  faCommentsDollar,
  faCompactDisc,
  faCompass,
  faCompassDrafting,
  faCompress,
  faComputer,
  faComputerMouse,
  faCookie,
  faCookieBite,
  faCopy,
  faCopyright,
  faCouch,
  faCow,
  faCreditCard,
  faCrop,
  faCropSimple,
  faCross,
  faCrosshairs,
  faCrow,
  faCrown,
  faCrutch,
  faCruzeiroSign,
  faCube,
  faCubes,
  faCubesStacked,
  faD,
  faDatabase,
  faDeleteLeft,
  faDemocrat,
  faDesktop,
  faDharmachakra,
  faDiagramNext,
  faDiagramPredecessor,
  faDiagramProject,
  faDiagramSuccessor,
  faDiamond,
  faDiamondTurnRight,
  faDice,
  faDiceD20,
  faDiceD6,
  faDiceFive,
  faDiceFour,
  faDiceOne,
  faDiceSix,
  faDiceThree,
  faDiceTwo,
  faDisease,
  faDisplay,
  faDivide,
  faDna,
  faDog,
  faDollarSign,
  faDolly,
  faDongSign,
  faDoorClosed,
  faDoorOpen,
  faDove,
  faDownLeftAndUpRightToCenter,
  faDownLong,
  faDownload,
  faDragon,
  faDrawPolygon,
  faDroplet,
  faDropletSlash,
  faDrum,
  faDrumSteelpan,
  faDrumstickBite,
  faDumbbell,
  faDumpster,
  faDumpsterFire,
  faDungeon,
  faE,
  faEarDeaf,
  faEarListen,
  faEarthAfrica,
  faEarthAmericas,
  faEarthAsia,
  faEarthEurope,
  faEarthOceania,
  faEgg,
  faEject,
  faElevator,
  faEllipsis,
  faEllipsisVertical,
  faEnvelope,
  faEnvelopeCircleCheck,
  faEnvelopeOpen,
  faEnvelopeOpenText,
  faEnvelopesBulk,
  faEquals,
  faEraser,
  faEthernet,
  faEuroSign,
  faExclamation,
  faExpand,
  faExplosion,
  faEye,
  faEyeDropper,
  faEyeLowVision,
  faEyeSlash,
  faF,
  faFaceAngry,
  faFaceDizzy,
  faFaceFlushed,
  faFaceFrown,
  faFaceFrownOpen,
  faFaceGrimace,
  faFaceGrin,
  faFaceGrinBeam,
  faFaceGrinBeamSweat,
  faFaceGrinHearts,
  faFaceGrinSquint,
  faFaceGrinSquintTears,
  faFaceGrinStars,
  faFaceGrinTears,
  faFaceGrinTongue,
  faFaceGrinTongueSquint,
  faFaceGrinTongueWink,
  faFaceGrinWide,
  faFaceGrinWink,
  faFaceKiss,
  faFaceKissBeam,
  faFaceKissWinkHeart,
  faFaceLaugh,
  faFaceLaughBeam,
  faFaceLaughSquint,
  faFaceLaughWink,
  faFaceMeh,
  faFaceMehBlank,
  faFaceRollingEyes,
  faFaceSadCry,
  faFaceSadTear,
  faFaceSmile,
  faFaceSmileBeam,
  faFaceSmileWink,
  faFaceSurprise,
  faFaceTired,
  faFan,
  faFaucet,
  faFaucetDrip,
  faFax,
  faFeather,
  faFeatherPointed,
  faFerry,
  faFile,
  faFileArrowDown,
  faFileArrowUp,
  faFileAudio,
  faFileCircleCheck,
  faFileCircleExclamation,
  faFileCircleMinus,
  faFileCirclePlus,
  faFileCircleQuestion,
  faFileCircleXmark,
  faFileCode,
  faFileContract,
  faFileCsv,
  faFileExcel,
  faFileExport,
  faFileFragment,
  faFileHalfDashed,
  faFileImage,
  faFileImport,
  faFileInvoice,
  faFileInvoiceDollar,
  faFileLines,
  faFileMedical,
  faFilePdf,
  faFilePen,
  faFilePowerpoint,
  faFilePrescription,
  faFileShield,
  faFileSignature,
  faFileVideo,
  faFileWaveform,
  faFileWord,
  faFileZipper,
  faFill,
  faFillDrip,
  faFilm,
  faFilter,
  faFilterCircleDollar,
  faFilterCircleXmark,
  faFingerprint,
  faFire,
  faFireBurner,
  faFireExtinguisher,
  faFireFlameCurved,
  faFireFlameSimple,
  faFish,
  faFishFins,
  faFlag,
  faFlagCheckered,
  faFlagUsa,
  faFlask,
  faFlaskVial,
  faFloppyDisk,
  faFlorinSign,
  faFolder,
  faFolderClosed,
  faFolderMinus,
  faFolderOpen,
  faFolderPlus,
  faFolderTree,
  faFont,
  faFontAwesome,
  faFootball,
  faForward,
  faForwardFast,
  faForwardStep,
  faFrancSign,
  faFrog,
  faFutbol,
  faG,
  faGamepad,
  faGasPump,
  faGauge,
  faGaugeHigh,
  faGaugeSimple,
  faGaugeSimpleHigh,
  faGavel,
  faGear,
  faGears,
  faGem,
  faGemini,
  faGenderless,
  faGhost,
  faGift,
  faGifts,
  faGlassWater,
  faGlassWaterDroplet,
  faGlasses,
  faGlobe,
  faGolfBallTee,
  faGopuram,
  faGraduationCap,
  faGreaterThan,
  faGreaterThanEqual,
  faGrip,
  faGripLines,
  faGripLinesVertical,
  faGripVertical,
  faGroupArrowsRotate,
  faGuaraniSign,
  faGuitar,
  faGun,
  faH,
  faHammer,
  faHamsa,
  faHand,
  faHandBackFist,
  faHandDots,
  faHandFist,
  faHandHolding,
  faHandHoldingDollar,
  faHandHoldingDroplet,
  faHandHoldingHand,
  faHandHoldingHeart,
  faHandHoldingMedical,
  faHandLizard,
  faHandMiddleFinger,
  faHandPeace,
  faHandPointDown,
  faHandPointLeft,
  faHandPointRight,
  faHandPointUp,
  faHandPointer,
  faHandScissors,
  faHandSparkles,
  faHandSpock,
  faHandcuffs,
  faHands,
  faHandsAslInterpreting,
  faHandsBound,
  faHandsBubbles,
  faHandsClapping,
  faHandsHolding,
  faHandsHoldingChild,
  faHandsHoldingCircle,
  faHandsPraying,
  faHandshake,
  faHandshakeAngle,
  faHandshakeSlash,
  faHanukiah,
  faHardDrive,
  faHashtag,
  faHatCowboy,
  faHatCowboySide,
  faHatWizard,
  faHeadSideCough,
  faHeadSideCoughSlash,
  faHeadSideMask,
  faHeadSideVirus,
  faHeading,
  faHeadphones,
  faHeadset,
  faHeart,
  faHeartCircleBolt,
  faHeartCircleCheck,
  faHeartCircleExclamation,
  faHeartCircleMinus,
  faHeartCirclePlus,
  faHeartCircleXmark,
  faHeartCrack,
  faHeartPulse,
  faHelicopter,
  faHelicopterSymbol,
  faHelmetSafety,
  faHelmetUn,
  faHexagon,
  faHexagonNodes,
  faHexagonNodesBolt,
  faHighlighter,
  faHillAvalanche,
  faHillRockslide,
  faHippo,
  faHockeyPuck,
  faHollyBerry,
  faHorse,
  faHorseHead,
  faHospital,
  faHospitalUser,
  faHotTubPerson,
  faHotdog,
  faHotel,
  faHourglass,
  faHourglassEnd,
  faHourglassHalf,
  faHourglassStart,
  faHouse,
  faHouseChimney,
  faHouseChimneyCrack,
  faHouseChimneyMedical,
  faHouseChimneyUser,
  faHouseChimneyWindow,
  faHouseCircleCheck,
  faHouseCircleExclamation,
  faHouseCircleXmark,
  faHouseCrack,
  faHouseFire,
  faHouseFlag,
  faHouseFloodWater,
  faHouseFloodWaterCircleArrowRight,
  faHouseLaptop,
  faHouseLock,
  faHouseMedical,
  faHouseMedicalCircleCheck,
  faHouseMedicalCircleExclamation,
  faHouseMedicalCircleXmark,
  faHouseMedicalFlag,
  faHouseSignal,
  faHouseTsunami,
  faHouseUser,
  faHryvniaSign,
  faHurricane,
  faI,
  faICursor,
  faIceCream,
  faIcicles,
  faIcons,
  faIdBadge,
  faIdCard,
  faIdCardClip,
  faIgloo,
  faImage,
  faImagePortrait,
  faImages,
  faInbox,
  faIndent,
  faIndianRupeeSign,
  faIndustry,
  faInfinity,
  faInfo,
  faItalic,
  faJ,
  faJar,
  faJarWheat,
  faJedi,
  faJetFighter,
  faJetFighterUp,
  faJoint,
  faJugDetergent,
  faK,
  faKaaba,
  faKey,
  faKeyboard,
  faKhanda,
  faKipSign,
  faKitMedical,
  faKitchenSet,
  faKiwiBird,
  faL,
  faLandMineOn,
  faLandmark,
  faLandmarkDome,
  faLandmarkFlag,
  faLanguage,
  faLaptop,
  faLaptopCode,
  faLaptopFile,
  faLaptopMedical,
  faLariSign,
  faLayerGroup,
  faLeaf,
  faLeftLong,
  faLeftRight,
  faLemon,
  faLeo,
  faLessThan,
  faLessThanEqual,
  faLibra,
  faLifeRing,
  faLightbulb,
  faLinesLeaning,
  faLink,
  faLinkSlash,
  faLiraSign,
  faList,
  faListCheck,
  faListOl,
  faListUl,
  faLitecoinSign,
  faLocationArrow,
  faLocationCrosshairs,
  faLocationDot,
  faLocationPin,
  faLocationPinLock,
  faLock,
  faLockOpen,
  faLocust,
  faLungs,
  faLungsVirus,
  faM,
  faMagnet,
  faMagnifyingGlass,
  faMagnifyingGlassArrowRight,
  faMagnifyingGlassChart,
  faMagnifyingGlassDollar,
  faMagnifyingGlassLocation,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faManatSign,
  faMap,
  faMapLocation,
  faMapLocationDot,
  faMapPin,
  faMarker,
  faMars,
  faMarsAndVenus,
  faMarsAndVenusBurst,
  faMarsDouble,
  faMarsStroke,
  faMarsStrokeRight,
  faMarsStrokeUp,
  faMartiniGlass,
  faMartiniGlassCitrus,
  faMartiniGlassEmpty,
  faMask,
  faMaskFace,
  faMaskVentilator,
  faMasksTheater,
  faMattressPillow,
  faMaximize,
  faMedal,
  faMemory,
  faMenorah,
  faMercury,
  faMessage,
  faMeteor,
  faMicrochip,
  faMicrophone,
  faMicrophoneLines,
  faMicrophoneLinesSlash,
  faMicrophoneSlash,
  faMicroscope,
  faMillSign,
  faMinimize,
  faMinus,
  faMitten,
  faMobile,
  faMobileButton,
  faMobileRetro,
  faMobileScreen,
  faMobileScreenButton,
  faMobileVibrate,
  faMoneyBill,
  faMoneyBill1,
  faMoneyBill1Wave,
  faMoneyBillTransfer,
  faMoneyBillTrendUp,
  faMoneyBillWave,
  faMoneyBillWheat,
  faMoneyBills,
  faMoneyCheck,
  faMoneyCheckDollar,
  faMonument,
  faMoon,
  faMortarPestle,
  faMosque,
  faMosquito,
  faMosquitoNet,
  faMotorcycle,
  faMound,
  faMountain,
  faMountainCity,
  faMountainSun,
  faMugHot,
  faMugSaucer,
  faMusic,
  faN,
  faNairaSign,
  faNetworkWired,
  faNeuter,
  faNewspaper,
  faNonBinary,
  faNotEqual,
  faNotdef,
  faNoteSticky,
  faNotesMedical,
  faO,
  faObjectGroup,
  faObjectUngroup,
  faOctagon,
  faOilCan,
  faOilWell,
  faOm,
  faOtter,
  faOutdent,
  faP,
  faPager,
  faPaintRoller,
  faPaintbrush,
  faPalette,
  faPallet,
  faPanorama,
  faPaperPlane,
  faPaperclip,
  faParachuteBox,
  faParagraph,
  faPassport,
  faPaste,
  faPause,
  faPaw,
  faPeace,
  faPen,
  faPenClip,
  faPenFancy,
  faPenNib,
  faPenRuler,
  faPenToSquare,
  faPencil,
  faPentagon,
  faPeopleArrows,
  faPeopleCarryBox,
  faPeopleGroup,
  faPeopleLine,
  faPeoplePulling,
  faPeopleRobbery,
  faPeopleRoof,
  faPepperHot,
  faPercent,
  faPerson,
  faPersonArrowDownToLine,
  faPersonArrowUpFromLine,
  faPersonBiking,
  faPersonBooth,
  faPersonBreastfeeding,
  faPersonBurst,
  faPersonCane,
  faPersonChalkboard,
  faPersonCircleCheck,
  faPersonCircleExclamation,
  faPersonCircleMinus,
  faPersonCirclePlus,
  faPersonCircleQuestion,
  faPersonCircleXmark,
  faPersonDigging,
  faPersonDotsFromLine,
  faPersonDress,
  faPersonDressBurst,
  faPersonDrowning,
  faPersonFalling,
  faPersonFallingBurst,
  faPersonHalfDress,
  faPersonHarassing,
  faPersonHiking,
  faPersonMilitaryPointing,
  faPersonMilitaryRifle,
  faPersonMilitaryToPerson,
  faPersonPraying,
  faPersonPregnant,
  faPersonRays,
  faPersonRifle,
  faPersonRunning,
  faPersonShelter,
  faPersonSkating,
  faPersonSkiing,
  faPersonSkiingNordic,
  faPersonSnowboarding,
  faPersonSwimming,
  faPersonThroughWindow,
  faPersonWalking,
  faPersonWalkingArrowLoopLeft,
  faPersonWalkingArrowRight,
  faPersonWalkingDashedLineArrowRight,
  faPersonWalkingLuggage,
  faPersonWalkingWithCane,
  faPesetaSign,
  faPesoSign,
  faPhone,
  faPhoneFlip,
  faPhoneSlash,
  faPhoneVolume,
  faPhotoFilm,
  faPictureInPicture,
  faPiggyBank,
  faPills,
  faPisces,
  faPizzaSlice,
  faPlaceOfWorship,
  faPlane,
  faPlaneArrival,
  faPlaneCircleCheck,
  faPlaneCircleExclamation,
  faPlaneCircleXmark,
  faPlaneDeparture,
  faPlaneLock,
  faPlaneSlash,
  faPlaneUp,
  faPlantWilt,
  faPlateWheat,
  faPlay,
  faPlug,
  faPlugCircleBolt,
  faPlugCircleCheck,
  faPlugCircleExclamation,
  faPlugCircleMinus,
  faPlugCirclePlus,
  faPlugCircleXmark,
  faPlus,
  faPlusMinus,
  faPodcast,
  faPoo,
  faPooStorm,
  faPoop,
  faPowerOff,
  faPrescription,
  faPrescriptionBottle,
  faPrescriptionBottleMedical,
  faPrint,
  faPumpMedical,
  faPumpSoap,
  faPuzzlePiece,
  faQ,
  faQrcode,
  faQuestion,
  faQuoteLeft,
  faQuoteRight,
  faR,
  faRadiation,
  faRadio,
  faRainbow,
  faRankingStar,
  faReceipt,
  faRecordVinyl,
  faRectangleAd,
  faRectangleList,
  faRectangleXmark,
  faRecycle,
  faRegistered,
  faRepeat,
  faReply,
  faReplyAll,
  faRepublican,
  faRestroom,
  faRetweet,
  faRibbon,
  faRightFromBracket,
  faRightLeft,
  faRightLong,
  faRightToBracket,
  faRing,
  faRoad,
  faRoadBarrier,
  faRoadBridge,
  faRoadCircleCheck,
  faRoadCircleExclamation,
  faRoadCircleXmark,
  faRoadLock,
  faRoadSpikes,
  faRobot,
  faRocket,
  faRotate,
  faRotateLeft,
  faRotateRight,
  faRoute,
  faRss,
  faRubleSign,
  faRug,
  faRuler,
  faRulerCombined,
  faRulerHorizontal,
  faRulerVertical,
  faRupeeSign,
  faRupiahSign,
  faS,
  faSackDollar,
  faSackXmark,
  faSagittarius,
  faSailboat,
  faSatellite,
  faSatelliteDish,
  faScaleBalanced,
  faScaleUnbalanced,
  faScaleUnbalancedFlip,
  faSchool,
  faSchoolCircleCheck,
  faSchoolCircleExclamation,
  faSchoolCircleXmark,
  faSchoolFlag,
  faSchoolLock,
  faScissors,
  faScorpio,
  faScrewdriver,
  faScrewdriverWrench,
  faScroll,
  faScrollTorah,
  faSdCard,
  faSection,
  faSeedling,
  faSeptagon,
  faServer,
  faShapes,
  faShare,
  faShareFromSquare,
  faShareNodes,
  faSheetPlastic,
  faShekelSign,
  faShield,
  faShieldCat,
  faShieldDog,
  faShieldHalved,
  faShieldHeart,
  faShieldVirus,
  faShip,
  faShirt,
  faShoePrints,
  faShop,
  faShopLock,
  faShopSlash,
  faShower,
  faShrimp,
  faShuffle,
  faShuttleSpace,
  faSignHanging,
  faSignal,
  faSignature,
  faSignsPost,
  faSimCard,
  faSingleQuoteLeft,
  faSingleQuoteRight,
  faSink,
  faSitemap,
  faSkull,
  faSkullCrossbones,
  faSlash,
  faSleigh,
  faSliders,
  faSmog,
  faSmoking,
  faSnowflake,
  faSnowman,
  faSnowplow,
  faSoap,
  faSocks,
  faSolarPanel,
  faSort,
  faSortDown,
  faSortUp,
  faSpa,
  faSpaghettiMonsterFlying,
  faSpellCheck,
  faSpider,
  faSpinner,
  faSpiral,
  faSplotch,
  faSpoon,
  faSprayCan,
  faSprayCanSparkles,
  faSquare,
  faSquareArrowUpRight,
  faSquareBinary,
  faSquareCaretDown,
  faSquareCaretLeft,
  faSquareCaretRight,
  faSquareCaretUp,
  faSquareCheck,
  faSquareEnvelope,
  faSquareFull,
  faSquareH,
  faSquareMinus,
  faSquareNfi,
  faSquareParking,
  faSquarePen,
  faSquarePersonConfined,
  faSquarePhone,
  faSquarePhoneFlip,
  faSquarePlus,
  faSquarePollHorizontal,
  faSquarePollVertical,
  faSquareRootVariable,
  faSquareRss,
  faSquareShareNodes,
  faSquareUpRight,
  faSquareVirus,
  faSquareXmark,
  faStaffSnake,
  faStairs,
  faStamp,
  faStapler,
  faStar,
  faStarAndCrescent,
  faStarHalf,
  faStarHalfStroke,
  faStarOfDavid,
  faStarOfLife,
  faSterlingSign,
  faStethoscope,
  faStop,
  faStopwatch,
  faStopwatch20,
  faStore,
  faStoreSlash,
  faStreetView,
  faStrikethrough,
  faStroopwafel,
  faSubscript,
  faSuitcase,
  faSuitcaseMedical,
  faSuitcaseRolling,
  faSun,
  faSunPlantWilt,
  faSuperscript,
  faSwatchbook,
  faSynagogue,
  faSyringe,
  faT,
  faTable,
  faTableCells,
  faTableCellsColumnLock,
  faTableCellsLarge,
  faTableCellsRowLock,
  faTableCellsRowUnlock,
  faTableColumns,
  faTableList,
  faTableTennisPaddleBall,
  faTablet,
  faTabletButton,
  faTabletScreenButton,
  faTablets,
  faTachographDigital,
  faTag,
  faTags,
  faTape,
  faTarp,
  faTarpDroplet,
  faTaurus,
  faTaxi,
  faTeeth,
  faTeethOpen,
  faTemperatureArrowDown,
  faTemperatureArrowUp,
  faTemperatureEmpty,
  faTemperatureFull,
  faTemperatureHalf,
  faTemperatureHigh,
  faTemperatureLow,
  faTemperatureQuarter,
  faTemperatureThreeQuarters,
  faTengeSign,
  faTent,
  faTentArrowDownToLine,
  faTentArrowLeftRight,
  faTentArrowTurnLeft,
  faTentArrowsDown,
  faTents,
  faTerminal,
  faTextHeight,
  faTextSlash,
  faTextWidth,
  faThermometer,
  faThumbsDown,
  faThumbsUp,
  faThumbtack,
  faThumbtackSlash,
  faTicket,
  faTicketSimple,
  faTimeline,
  faToggleOff,
  faToggleOn,
  faToilet,
  faToiletPaper,
  faToiletPaperSlash,
  faToiletPortable,
  faToiletsPortable,
  faToolbox,
  faTooth,
  faToriiGate,
  faTornado,
  faTowerBroadcast,
  faTowerCell,
  faTowerObservation,
  faTractor,
  faTrademark,
  faTrafficLight,
  faTrailer,
  faTrain,
  faTrainSubway,
  faTrainTram,
  faTransgender,
  faTrash,
  faTrashArrowUp,
  faTrashCan,
  faTrashCanArrowUp,
  faTree,
  faTreeCity,
  faTriangleExclamation,
  faTrophy,
  faTrowel,
  faTrowelBricks,
  faTruck,
  faTruckArrowRight,
  faTruckDroplet,
  faTruckFast,
  faTruckField,
  faTruckFieldUn,
  faTruckFront,
  faTruckMedical,
  faTruckMonster,
  faTruckMoving,
  faTruckPickup,
  faTruckPlane,
  faTruckRampBox,
  faTty,
  faTurkishLiraSign,
  faTurnDown,
  faTurnUp,
  faTv,
  faU,
  faUmbrella,
  faUmbrellaBeach,
  faUnderline,
  faUniversalAccess,
  faUnlock,
  faUnlockKeyhole,
  faUpDown,
  faUpDownLeftRight,
  faUpLong,
  faUpRightAndDownLeftFromCenter,
  faUpRightFromSquare,
  faUpload,
  faUser,
  faUserAstronaut,
  faUserCheck,
  faUserClock,
  faUserDoctor,
  faUserGear,
  faUserGraduate,
  faUserGroup,
  faUserInjured,
  faUserLock,
  faUserMinus,
  faUserNinja,
  faUserNurse,
  faUserPen,
  faUserPlus,
  faUserSecret,
  faUserShield,
  faUserSlash,
  faUserTag,
  faUserTie,
  faUserXmark,
  faUsers,
  faUsersBetweenLines,
  faUsersGear,
  faUsersLine,
  faUsersRays,
  faUsersRectangle,
  faUsersSlash,
  faUsersViewfinder,
  faUtensils,
  faV,
  faVanShuttle,
  faVault,
  faVenus,
  faVenusDouble,
  faVenusMars,
  faVest,
  faVestPatches,
  faVial,
  faVialCircleCheck,
  faVialVirus,
  faVials,
  faVideo,
  faVideoSlash,
  faVihara,
  faVirgo,
  faVirus,
  faVirusCovid,
  faVirusCovidSlash,
  faVirusSlash,
  faViruses,
  faVoicemail,
  faVolcano,
  faVolleyball,
  faVolume,
  faVolumeHigh,
  faVolumeLow,
  faVolumeOff,
  faVolumeXmark,
  faVrCardboard,
  faW,
  faWalkieTalkie,
  faWallet,
  faWandMagic,
  faWandMagicSparkles,
  faWandSparkles,
  faWarehouse,
  faWater,
  faWaterLadder,
  faWaveSquare,
  faWebAwesome,
  faWeightHanging,
  faWeightScale,
  faWheatAwn,
  faWheatAwnCircleExclamation,
  faWheelchair,
  faWheelchairMove,
  faWhiskeyGlass,
  faWifi,
  faWind,
  faWindowMaximize,
  faWindowMinimize,
  faWindowRestore,
  faWineBottle,
  faWineGlass,
  faWineGlassEmpty,
  faWonSign,
  faWorm,
  faWrench,
  faX,
  faXRay,
  faXmark,
  faXmarksLines,
  faY,
  faYenSign,
  faYinYang,
  faZ,
} from "@fortawesome/free-solid-svg-icons";

import {
  faAddressBook as faAddressBookOutline,
  faAddressCard as faAddressCardOutline,
  faAlarmClock as faAlarmClockOutline,
  faBell as faBellOutline,
  faBellSlash as faBellSlashOutline,
  faBookmark as faBookmarkOutline,
  faBuilding as faBuildingOutline,
  faCalendar as faCalendarOutline,
  faCalendarCheck as faCalendarCheckOutline,
  faCalendarDays as faCalendarDaysOutline,
  faCalendarMinus as faCalendarMinusOutline,
  faCalendarPlus as faCalendarPlusOutline,
  faCalendarXmark as faCalendarXmarkOutline,
  faCamera as faCameraOutline,
  faChartBar as faChartBarOutline,
  faChessBishop as faChessBishopOutline,
  faChessKing as faChessKingOutline,
  faChessKnight as faChessKnightOutline,
  faChessPawn as faChessPawnOutline,
  faChessQueen as faChessQueenOutline,
  faChessRook as faChessRookOutline,
  faCircle as faCircleOutline,
  faCircleCheck as faCircleCheckOutline,
  faCircleDot as faCircleDotOutline,
  faCircleDown as faCircleDownOutline,
  faCircleLeft as faCircleLeftOutline,
  faCirclePause as faCirclePauseOutline,
  faCirclePlay as faCirclePlayOutline,
  faCircleQuestion as faCircleQuestionOutline,
  faCircleRight as faCircleRightOutline,
  faCircleStop as faCircleStopOutline,
  faCircleUp as faCircleUpOutline,
  faCircleUser as faCircleUserOutline,
  faCircleXmark as faCircleXmarkOutline,
  faClipboard as faClipboardOutline,
  faClock as faClockOutline,
  faClone as faCloneOutline,
  faClosedCaptioning as faClosedCaptioningOutline,
  faCloud as faCloudOutline,
  faComment as faCommentOutline,
  faCommentDots as faCommentDotsOutline,
  faComments as faCommentsOutline,
  faCompass as faCompassOutline,
  faCopy as faCopyOutline,
  faCopyright as faCopyrightOutline,
  faCreditCard as faCreditCardOutline,
  faEnvelope as faEnvelopeOutline,
  faEnvelopeOpen as faEnvelopeOpenOutline,
  faEye as faEyeOutline,
  faEyeSlash as faEyeSlashOutline,
  faFaceAngry as faFaceAngryOutline,
  faFaceDizzy as faFaceDizzyOutline,
  faFaceFlushed as faFaceFlushedOutline,
  faFaceFrown as faFaceFrownOutline,
  faFaceFrownOpen as faFaceFrownOpenOutline,
  faFaceGrimace as faFaceGrimaceOutline,
  faFaceGrin as faFaceGrinOutline,
  faFaceGrinBeam as faFaceGrinBeamOutline,
  faFaceGrinBeamSweat as faFaceGrinBeamSweatOutline,
  faFaceGrinHearts as faFaceGrinHeartsOutline,
  faFaceGrinSquint as faFaceGrinSquintOutline,
  faFaceGrinSquintTears as faFaceGrinSquintTearsOutline,
  faFaceGrinStars as faFaceGrinStarsOutline,
  faFaceGrinTears as faFaceGrinTearsOutline,
  faFaceGrinTongue as faFaceGrinTongueOutline,
  faFaceGrinTongueSquint as faFaceGrinTongueSquintOutline,
  faFaceGrinTongueWink as faFaceGrinTongueWinkOutline,
  faFaceGrinWide as faFaceGrinWideOutline,
  faFaceGrinWink as faFaceGrinWinkOutline,
  faFaceKiss as faFaceKissOutline,
  faFaceKissBeam as faFaceKissBeamOutline,
  faFaceKissWinkHeart as faFaceKissWinkHeartOutline,
  faFaceLaugh as faFaceLaughOutline,
  faFaceLaughBeam as faFaceLaughBeamOutline,
  faFaceLaughSquint as faFaceLaughSquintOutline,
  faFaceLaughWink as faFaceLaughWinkOutline,
  faFaceMeh as faFaceMehOutline,
  faFaceMehBlank as faFaceMehBlankOutline,
  faFaceRollingEyes as faFaceRollingEyesOutline,
  faFaceSadCry as faFaceSadCryOutline,
  faFaceSadTear as faFaceSadTearOutline,
  faFaceSmile as faFaceSmileOutline,
  faFaceSmileBeam as faFaceSmileBeamOutline,
  faFaceSmileWink as faFaceSmileWinkOutline,
  faFaceSurprise as faFaceSurpriseOutline,
  faFaceTired as faFaceTiredOutline,
  faFile as faFileOutline,
  faFileAudio as faFileAudioOutline,
  faFileCode as faFileCodeOutline,
  faFileExcel as faFileExcelOutline,
  faFileImage as faFileImageOutline,
  faFileLines as faFileLinesOutline,
  faFilePdf as faFilePdfOutline,
  faFilePowerpoint as faFilePowerpointOutline,
  faFileVideo as faFileVideoOutline,
  faFileWord as faFileWordOutline,
  faFileZipper as faFileZipperOutline,
  faFlag as faFlagOutline,
  faFloppyDisk as faFloppyDiskOutline,
  faFolder as faFolderOutline,
  faFolderClosed as faFolderClosedOutline,
  faFolderOpen as faFolderOpenOutline,
  faFontAwesome as faFontAwesomeOutline,
  faFutbol as faFutbolOutline,
  faGem as faGemOutline,
  faHand as faHandOutline,
  faHandBackFist as faHandBackFistOutline,
  faHandLizard as faHandLizardOutline,
  faHandPeace as faHandPeaceOutline,
  faHandPointDown as faHandPointDownOutline,
  faHandPointLeft as faHandPointLeftOutline,
  faHandPointRight as faHandPointRightOutline,
  faHandPointUp as faHandPointUpOutline,
  faHandPointer as faHandPointerOutline,
  faHandScissors as faHandScissorsOutline,
  faHandSpock as faHandSpockOutline,
  faHandshake as faHandshakeOutline,
  faHardDrive as faHardDriveOutline,
  faHeadphones as faHeadphonesOutline,
  faHeart as faHeartOutline,
  faHospital as faHospitalOutline,
  faHourglass as faHourglassOutline,
  faHourglassHalf as faHourglassHalfOutline,
  faHouse as faHouseOutline,
  faIdBadge as faIdBadgeOutline,
  faIdCard as faIdCardOutline,
  faImage as faImageOutline,
  faImages as faImagesOutline,
  faKeyboard as faKeyboardOutline,
  faLemon as faLemonOutline,
  faLifeRing as faLifeRingOutline,
  faLightbulb as faLightbulbOutline,
  faMap as faMapOutline,
  faMessage as faMessageOutline,
  faMoneyBill1 as faMoneyBill1Outline,
  faMoon as faMoonOutline,
  faNewspaper as faNewspaperOutline,
  faNoteSticky as faNoteStickyOutline,
  faObjectGroup as faObjectGroupOutline,
  faObjectUngroup as faObjectUngroupOutline,
  faPaperPlane as faPaperPlaneOutline,
  faPaste as faPasteOutline,
  faPenToSquare as faPenToSquareOutline,
  faRectangleList as faRectangleListOutline,
  faRectangleXmark as faRectangleXmarkOutline,
  faRegistered as faRegisteredOutline,
  faShareFromSquare as faShareFromSquareOutline,
  faSnowflake as faSnowflakeOutline,
  faSquare as faSquareOutline,
  faSquareCaretDown as faSquareCaretDownOutline,
  faSquareCaretLeft as faSquareCaretLeftOutline,
  faSquareCaretRight as faSquareCaretRightOutline,
  faSquareCaretUp as faSquareCaretUpOutline,
  faSquareCheck as faSquareCheckOutline,
  faSquareFull as faSquareFullOutline,
  faSquareMinus as faSquareMinusOutline,
  faSquarePlus as faSquarePlusOutline,
  faStar as faStarOutline,
  faStarHalf as faStarHalfOutline,
  faStarHalfStroke as faStarHalfStrokeOutline,
  faSun as faSunOutline,
  faThumbsDown as faThumbsDownOutline,
  faThumbsUp as faThumbsUpOutline,
  faTrashCan as faTrashCanOutline,
  faTruck as faTruckOutline,
  faUser as faUserOutline,
  faWindowMaximize as faWindowMaximizeOutline,
  faWindowMinimize as faWindowMinimizeOutline,
  faWindowRestore as faWindowRestoreOutline,
} from "@fortawesome/free-regular-svg-icons";

/**
 * Map of string icon names to FA icon objects.
 * Keys use Font Awesome naming conventions (kebab-case icon names).
 *
 * - Bare key (e.g. "trash")           -> solid/filled style (default)
 * - "-outline" suffixed key (e.g. "trash-outline") -> regular/outline style
 * - A handful of semantic action aliases (edit, delete, deactivate,
 *   preview, restore, cancel, save) are kept at the top for backward
 *   compatibility with existing action-config code that references them.
 */
const ICON_MAP = Object.freeze({
  // ─────────────────────────────────────────────────────────
  // Explicit action aliases (semantic names -> concrete icon)
  // ─────────────────────────────────────────────────────────
  "edit": faPen,
  "delete": faTrash,
  "deactivate": faBan,
  "preview": faEyeOutline,
  "restore": faRotateLeft,
  "cancel": faXmark,
  "save": faFloppyDiskOutline,

  // ─────────────────────────────────────────────────────────
  // Solid icons (filled style) — bare kebab-case names.
  // This is the default/primary style for this app.
  // ─────────────────────────────────────────────────────────
  "0": fa0,
  "1": fa1,
  "2": fa2,
  "3": fa3,
  "4": fa4,
  "5": fa5,
  "6": fa6,
  "7": fa7,
  "8": fa8,
  "9": fa9,
  "a": faA,
  "address-book": faAddressBook,
  "address-card": faAddressCard,
  "alarm-clock": faAlarmClock,
  "align-center": faAlignCenter,
  "align-justify": faAlignJustify,
  "align-left": faAlignLeft,
  "align-right": faAlignRight,
  "anchor": faAnchor,
  "anchor-circle-check": faAnchorCircleCheck,
  "anchor-circle-exclamation": faAnchorCircleExclamation,
  "anchor-circle-xmark": faAnchorCircleXmark,
  "anchor-lock": faAnchorLock,
  "angle-down": faAngleDown,
  "angle-left": faAngleLeft,
  "angle-right": faAngleRight,
  "angle-up": faAngleUp,
  "angles-down": faAnglesDown,
  "angles-left": faAnglesLeft,
  "angles-right": faAnglesRight,
  "angles-up": faAnglesUp,
  "ankh": faAnkh,
  "apple-whole": faAppleWhole,
  "aquarius": faAquarius,
  "archway": faArchway,
  "aries": faAries,
  "arrow-down": faArrowDown,
  "arrow-down-1-9": faArrowDown19,
  "arrow-down-9-1": faArrowDown91,
  "arrow-down-a-z": faArrowDownAZ,
  "arrow-down-long": faArrowDownLong,
  "arrow-down-short-wide": faArrowDownShortWide,
  "arrow-down-up-across-line": faArrowDownUpAcrossLine,
  "arrow-down-up-lock": faArrowDownUpLock,
  "arrow-down-wide-short": faArrowDownWideShort,
  "arrow-down-z-a": faArrowDownZA,
  "arrow-left": faArrowLeft,
  "arrow-left-long": faArrowLeftLong,
  "arrow-pointer": faArrowPointer,
  "arrow-right": faArrowRight,
  "arrow-right-arrow-left": faArrowRightArrowLeft,
  "arrow-right-from-bracket": faArrowRightFromBracket,
  "arrow-right-long": faArrowRightLong,
  "arrow-right-to-bracket": faArrowRightToBracket,
  "arrow-right-to-city": faArrowRightToCity,
  "arrow-rotate-left": faArrowRotateLeft,
  "arrow-rotate-right": faArrowRotateRight,
  "arrow-trend-down": faArrowTrendDown,
  "arrow-trend-up": faArrowTrendUp,
  "arrow-turn-down": faArrowTurnDown,
  "arrow-turn-up": faArrowTurnUp,
  "arrow-up": faArrowUp,
  "arrow-up-1-9": faArrowUp19,
  "arrow-up-9-1": faArrowUp91,
  "arrow-up-a-z": faArrowUpAZ,
  "arrow-up-from-bracket": faArrowUpFromBracket,
  "arrow-up-from-ground-water": faArrowUpFromGroundWater,
  "arrow-up-from-water-pump": faArrowUpFromWaterPump,
  "arrow-up-long": faArrowUpLong,
  "arrow-up-right-dots": faArrowUpRightDots,
  "arrow-up-right-from-square": faArrowUpRightFromSquare,
  "arrow-up-short-wide": faArrowUpShortWide,
  "arrow-up-wide-short": faArrowUpWideShort,
  "arrow-up-z-a": faArrowUpZA,
  "arrows-down-to-line": faArrowsDownToLine,
  "arrows-down-to-people": faArrowsDownToPeople,
  "arrows-left-right": faArrowsLeftRight,
  "arrows-left-right-to-line": faArrowsLeftRightToLine,
  "arrows-rotate": faArrowsRotate,
  "arrows-spin": faArrowsSpin,
  "arrows-split-up-and-left": faArrowsSplitUpAndLeft,
  "arrows-to-circle": faArrowsToCircle,
  "arrows-to-dot": faArrowsToDot,
  "arrows-to-eye": faArrowsToEye,
  "arrows-turn-right": faArrowsTurnRight,
  "arrows-turn-to-dots": faArrowsTurnToDots,
  "arrows-up-down": faArrowsUpDown,
  "arrows-up-down-left-right": faArrowsUpDownLeftRight,
  "arrows-up-to-line": faArrowsUpToLine,
  "asterisk": faAsterisk,
  "at": faAt,
  "atom": faAtom,
  "audio-description": faAudioDescription,
  "austral-sign": faAustralSign,
  "award": faAward,
  "b": faB,
  "baby": faBaby,
  "baby-carriage": faBabyCarriage,
  "backward": faBackward,
  "backward-fast": faBackwardFast,
  "backward-step": faBackwardStep,
  "bacon": faBacon,
  "bacteria": faBacteria,
  "bacterium": faBacterium,
  "bag-shopping": faBagShopping,
  "bahai": faBahai,
  "baht-sign": faBahtSign,
  "ban": faBan,
  "ban-smoking": faBanSmoking,
  "bandage": faBandage,
  "bangladeshi-taka-sign": faBangladeshiTakaSign,
  "barcode": faBarcode,
  "bars": faBars,
  "bars-progress": faBarsProgress,
  "bars-staggered": faBarsStaggered,
  "baseball": faBaseball,
  "baseball-bat-ball": faBaseballBatBall,
  "basket-shopping": faBasketShopping,
  "basketball": faBasketball,
  "bath": faBath,
  "battery-empty": faBatteryEmpty,
  "battery-full": faBatteryFull,
  "battery-half": faBatteryHalf,
  "battery-quarter": faBatteryQuarter,
  "battery-three-quarters": faBatteryThreeQuarters,
  "bed": faBed,
  "bed-pulse": faBedPulse,
  "beer-mug-empty": faBeerMugEmpty,
  "bell": faBell,
  "bell-concierge": faBellConcierge,
  "bell-slash": faBellSlash,
  "bezier-curve": faBezierCurve,
  "bicycle": faBicycle,
  "binoculars": faBinoculars,
  "biohazard": faBiohazard,
  "bitcoin-sign": faBitcoinSign,
  "blender": faBlender,
  "blender-phone": faBlenderPhone,
  "blog": faBlog,
  "bold": faBold,
  "bolt": faBolt,
  "bolt-lightning": faBoltLightning,
  "bomb": faBomb,
  "bone": faBone,
  "bong": faBong,
  "book": faBook,
  "book-atlas": faBookAtlas,
  "book-bible": faBookBible,
  "book-bookmark": faBookBookmark,
  "book-journal-whills": faBookJournalWhills,
  "book-medical": faBookMedical,
  "book-open": faBookOpen,
  "book-open-reader": faBookOpenReader,
  "book-quran": faBookQuran,
  "book-skull": faBookSkull,
  "book-tanakh": faBookTanakh,
  "bookmark": faBookmark,
  "border-all": faBorderAll,
  "border-none": faBorderNone,
  "border-top-left": faBorderTopLeft,
  "bore-hole": faBoreHole,
  "bottle-droplet": faBottleDroplet,
  "bottle-water": faBottleWater,
  "bowl-food": faBowlFood,
  "bowl-rice": faBowlRice,
  "bowling-ball": faBowlingBall,
  "box": faBox,
  "box-archive": faBoxArchive,
  "box-open": faBoxOpen,
  "box-tissue": faBoxTissue,
  "boxes-packing": faBoxesPacking,
  "boxes-stacked": faBoxesStacked,
  "braille": faBraille,
  "brain": faBrain,
  "brazilian-real-sign": faBrazilianRealSign,
  "bread-slice": faBreadSlice,
  "bridge": faBridge,
  "bridge-circle-check": faBridgeCircleCheck,
  "bridge-circle-exclamation": faBridgeCircleExclamation,
  "bridge-circle-xmark": faBridgeCircleXmark,
  "bridge-lock": faBridgeLock,
  "bridge-water": faBridgeWater,
  "briefcase": faBriefcase,
  "briefcase-medical": faBriefcaseMedical,
  "broom": faBroom,
  "broom-ball": faBroomBall,
  "brush": faBrush,
  "bucket": faBucket,
  "bug": faBug,
  "bug-slash": faBugSlash,
  "bugs": faBugs,
  "building": faBuilding,
  "building-circle-arrow-right": faBuildingCircleArrowRight,
  "building-circle-check": faBuildingCircleCheck,
  "building-circle-exclamation": faBuildingCircleExclamation,
  "building-circle-xmark": faBuildingCircleXmark,
  "building-columns": faBuildingColumns,
  "building-flag": faBuildingFlag,
  "building-lock": faBuildingLock,
  "building-ngo": faBuildingNgo,
  "building-shield": faBuildingShield,
  "building-un": faBuildingUn,
  "building-user": faBuildingUser,
  "building-wheat": faBuildingWheat,
  "bullhorn": faBullhorn,
  "bullseye": faBullseye,
  "burger": faBurger,
  "burst": faBurst,
  "bus": faBus,
  "bus-side": faBusSide,
  "bus-simple": faBusSimple,
  "business-time": faBusinessTime,
  "c": faC,
  "cable-car": faCableCar,
  "cake-candles": faCakeCandles,
  "calculator": faCalculator,
  "calendar": faCalendar,
  "calendar-check": faCalendarCheck,
  "calendar-day": faCalendarDay,
  "calendar-days": faCalendarDays,
  "calendar-minus": faCalendarMinus,
  "calendar-plus": faCalendarPlus,
  "calendar-week": faCalendarWeek,
  "calendar-xmark": faCalendarXmark,
  "camera": faCamera,
  "camera-retro": faCameraRetro,
  "camera-rotate": faCameraRotate,
  "campground": faCampground,
  "cancer": faCancer,
  "candy-cane": faCandyCane,
  "cannabis": faCannabis,
  "capricorn": faCapricorn,
  "capsules": faCapsules,
  "car": faCar,
  "car-battery": faCarBattery,
  "car-burst": faCarBurst,
  "car-on": faCarOn,
  "car-rear": faCarRear,
  "car-side": faCarSide,
  "car-tunnel": faCarTunnel,
  "caravan": faCaravan,
  "caret-down": faCaretDown,
  "caret-left": faCaretLeft,
  "caret-right": faCaretRight,
  "caret-up": faCaretUp,
  "carrot": faCarrot,
  "cart-arrow-down": faCartArrowDown,
  "cart-flatbed": faCartFlatbed,
  "cart-flatbed-suitcase": faCartFlatbedSuitcase,
  "cart-plus": faCartPlus,
  "cart-shopping": faCartShopping,
  "cash-register": faCashRegister,
  "cat": faCat,
  "cedi-sign": faCediSign,
  "cent-sign": faCentSign,
  "certificate": faCertificate,
  "chair": faChair,
  "chalkboard": faChalkboard,
  "chalkboard-user": faChalkboardUser,
  "champagne-glasses": faChampagneGlasses,
  "charging-station": faChargingStation,
  "chart-area": faChartArea,
  "chart-bar": faChartBar,
  "chart-column": faChartColumn,
  "chart-diagram": faChartDiagram,
  "chart-gantt": faChartGantt,
  "chart-line": faChartLine,
  "chart-pie": faChartPie,
  "chart-simple": faChartSimple,
  "check": faCheck,
  "check-double": faCheckDouble,
  "check-to-slot": faCheckToSlot,
  "cheese": faCheese,
  "chess": faChess,
  "chess-bishop": faChessBishop,
  "chess-board": faChessBoard,
  "chess-king": faChessKing,
  "chess-knight": faChessKnight,
  "chess-pawn": faChessPawn,
  "chess-queen": faChessQueen,
  "chess-rook": faChessRook,
  "chevron-down": faChevronDown,
  "chevron-left": faChevronLeft,
  "chevron-right": faChevronRight,
  "chevron-up": faChevronUp,
  "child": faChild,
  "child-combatant": faChildCombatant,
  "child-dress": faChildDress,
  "child-reaching": faChildReaching,
  "children": faChildren,
  "church": faChurch,
  "circle": faCircle,
  "circle-arrow-down": faCircleArrowDown,
  "circle-arrow-left": faCircleArrowLeft,
  "circle-arrow-right": faCircleArrowRight,
  "circle-arrow-up": faCircleArrowUp,
  "circle-chevron-down": faCircleChevronDown,
  "circle-chevron-left": faCircleChevronLeft,
  "circle-chevron-right": faCircleChevronRight,
  "circle-chevron-up": faCircleChevronUp,
  "circle-dollar-to-slot": faCircleDollarToSlot,
  "circle-dot": faCircleDot,
  "circle-down": faCircleDown,
  "circle-exclamation": faCircleExclamation,
  "circle-h": faCircleH,
  "circle-half-stroke": faCircleHalfStroke,
  "circle-info": faCircleInfo,
  "circle-left": faCircleLeft,
  "circle-minus": faCircleMinus,
  "circle-nodes": faCircleNodes,
  "circle-notch": faCircleNotch,
  "circle-pause": faCirclePause,
  "circle-play": faCirclePlay,
  "circle-plus": faCirclePlus,
  "circle-question": faCircleQuestion,
  "circle-radiation": faCircleRadiation,
  "circle-right": faCircleRight,
  "circle-stop": faCircleStop,
  "circle-up": faCircleUp,
  "circle-user": faCircleUser,
  "city": faCity,
  "clapperboard": faClapperboard,
  "clipboard": faClipboard,
  "clipboard-check": faClipboardCheck,
  "clipboard-list": faClipboardList,
  "clipboard-question": faClipboardQuestion,
  "clipboard-user": faClipboardUser,
  "clock": faClock,
  "clock-rotate-left": faClockRotateLeft,
  "clone": faClone,
  "closed-captioning": faClosedCaptioning,
  "closed-captioning-slash": faClosedCaptioningSlash,
  "cloud": faCloud,
  "cloud-arrow-down": faCloudArrowDown,
  "cloud-arrow-up": faCloudArrowUp,
  "cloud-bolt": faCloudBolt,
  "cloud-meatball": faCloudMeatball,
  "cloud-moon": faCloudMoon,
  "cloud-moon-rain": faCloudMoonRain,
  "cloud-rain": faCloudRain,
  "cloud-showers-heavy": faCloudShowersHeavy,
  "cloud-showers-water": faCloudShowersWater,
  "cloud-sun": faCloudSun,
  "cloud-sun-rain": faCloudSunRain,
  "clover": faClover,
  "code": faCode,
  "code-branch": faCodeBranch,
  "code-commit": faCodeCommit,
  "code-compare": faCodeCompare,
  "code-fork": faCodeFork,
  "code-merge": faCodeMerge,
  "code-pull-request": faCodePullRequest,
  "coins": faCoins,
  "colon-sign": faColonSign,
  "comment": faComment,
  "comment-dollar": faCommentDollar,
  "comment-dots": faCommentDots,
  "comment-medical": faCommentMedical,
  "comment-nodes": faCommentNodes,
  "comment-slash": faCommentSlash,
  "comment-sms": faCommentSms,
  "comments": faComments,
  "comments-dollar": faCommentsDollar,
  "compact-disc": faCompactDisc,
  "compass": faCompass,
  "compass-drafting": faCompassDrafting,
  "compress": faCompress,
  "computer": faComputer,
  "computer-mouse": faComputerMouse,
  "cookie": faCookie,
  "cookie-bite": faCookieBite,
  "copy": faCopy,
  "copyright": faCopyright,
  "couch": faCouch,
  "cow": faCow,
  "credit-card": faCreditCard,
  "crop": faCrop,
  "crop-simple": faCropSimple,
  "cross": faCross,
  "crosshairs": faCrosshairs,
  "crow": faCrow,
  "crown": faCrown,
  "crutch": faCrutch,
  "cruzeiro-sign": faCruzeiroSign,
  "cube": faCube,
  "cubes": faCubes,
  "cubes-stacked": faCubesStacked,
  "d": faD,
  "database": faDatabase,
  "delete-left": faDeleteLeft,
  "democrat": faDemocrat,
  "desktop": faDesktop,
  "dharmachakra": faDharmachakra,
  "diagram-next": faDiagramNext,
  "diagram-predecessor": faDiagramPredecessor,
  "diagram-project": faDiagramProject,
  "diagram-successor": faDiagramSuccessor,
  "diamond": faDiamond,
  "diamond-turn-right": faDiamondTurnRight,
  "dice": faDice,
  "dice-d20": faDiceD20,
  "dice-d6": faDiceD6,
  "dice-five": faDiceFive,
  "dice-four": faDiceFour,
  "dice-one": faDiceOne,
  "dice-six": faDiceSix,
  "dice-three": faDiceThree,
  "dice-two": faDiceTwo,
  "disease": faDisease,
  "display": faDisplay,
  "divide": faDivide,
  "dna": faDna,
  "dog": faDog,
  "dollar-sign": faDollarSign,
  "dolly": faDolly,
  "dong-sign": faDongSign,
  "door-closed": faDoorClosed,
  "door-open": faDoorOpen,
  "dove": faDove,
  "down-left-and-up-right-to-center": faDownLeftAndUpRightToCenter,
  "down-long": faDownLong,
  "download": faDownload,
  "dragon": faDragon,
  "draw-polygon": faDrawPolygon,
  "droplet": faDroplet,
  "droplet-slash": faDropletSlash,
  "drum": faDrum,
  "drum-steelpan": faDrumSteelpan,
  "drumstick-bite": faDrumstickBite,
  "dumbbell": faDumbbell,
  "dumpster": faDumpster,
  "dumpster-fire": faDumpsterFire,
  "dungeon": faDungeon,
  "e": faE,
  "ear-deaf": faEarDeaf,
  "ear-listen": faEarListen,
  "earth-africa": faEarthAfrica,
  "earth-americas": faEarthAmericas,
  "earth-asia": faEarthAsia,
  "earth-europe": faEarthEurope,
  "earth-oceania": faEarthOceania,
  "egg": faEgg,
  "eject": faEject,
  "elevator": faElevator,
  "ellipsis": faEllipsis,
  "ellipsis-vertical": faEllipsisVertical,
  "envelope": faEnvelope,
  "envelope-circle-check": faEnvelopeCircleCheck,
  "envelope-open": faEnvelopeOpen,
  "envelope-open-text": faEnvelopeOpenText,
  "envelopes-bulk": faEnvelopesBulk,
  "equals": faEquals,
  "eraser": faEraser,
  "ethernet": faEthernet,
  "euro-sign": faEuroSign,
  "exclamation": faExclamation,
  "expand": faExpand,
  "explosion": faExplosion,
  "eye-dropper": faEyeDropper,
  "eye-low-vision": faEyeLowVision,
  "f": faF,
  "face-angry": faFaceAngry,
  "face-dizzy": faFaceDizzy,
  "face-flushed": faFaceFlushed,
  "face-frown": faFaceFrown,
  "face-frown-open": faFaceFrownOpen,
  "face-grimace": faFaceGrimace,
  "face-grin": faFaceGrin,
  "face-grin-beam": faFaceGrinBeam,
  "face-grin-beam-sweat": faFaceGrinBeamSweat,
  "face-grin-hearts": faFaceGrinHearts,
  "face-grin-squint": faFaceGrinSquint,
  "face-grin-squint-tears": faFaceGrinSquintTears,
  "face-grin-stars": faFaceGrinStars,
  "face-grin-tears": faFaceGrinTears,
  "face-grin-tongue": faFaceGrinTongue,
  "face-grin-tongue-squint": faFaceGrinTongueSquint,
  "face-grin-tongue-wink": faFaceGrinTongueWink,
  "face-grin-wide": faFaceGrinWide,
  "face-grin-wink": faFaceGrinWink,
  "face-kiss": faFaceKiss,
  "face-kiss-beam": faFaceKissBeam,
  "face-kiss-wink-heart": faFaceKissWinkHeart,
  "face-laugh": faFaceLaugh,
  "face-laugh-beam": faFaceLaughBeam,
  "face-laugh-squint": faFaceLaughSquint,
  "face-laugh-wink": faFaceLaughWink,
  "face-meh": faFaceMeh,
  "face-meh-blank": faFaceMehBlank,
  "face-rolling-eyes": faFaceRollingEyes,
  "face-sad-cry": faFaceSadCry,
  "face-sad-tear": faFaceSadTear,
  "face-smile": faFaceSmile,
  "face-smile-beam": faFaceSmileBeam,
  "face-smile-wink": faFaceSmileWink,
  "face-surprise": faFaceSurprise,
  "face-tired": faFaceTired,
  "fan": faFan,
  "faucet": faFaucet,
  "faucet-drip": faFaucetDrip,
  "fax": faFax,
  "feather": faFeather,
  "feather-pointed": faFeatherPointed,
  "ferry": faFerry,
  "file": faFile,
  "file-arrow-down": faFileArrowDown,
  "file-arrow-up": faFileArrowUp,
  "file-audio": faFileAudio,
  "file-circle-check": faFileCircleCheck,
  "file-circle-exclamation": faFileCircleExclamation,
  "file-circle-minus": faFileCircleMinus,
  "file-circle-plus": faFileCirclePlus,
  "file-circle-question": faFileCircleQuestion,
  "file-circle-xmark": faFileCircleXmark,
  "file-code": faFileCode,
  "file-contract": faFileContract,
  "file-csv": faFileCsv,
  "file-excel": faFileExcel,
  "file-export": faFileExport,
  "file-fragment": faFileFragment,
  "file-half-dashed": faFileHalfDashed,
  "file-image": faFileImage,
  "file-import": faFileImport,
  "file-invoice": faFileInvoice,
  "file-invoice-dollar": faFileInvoiceDollar,
  "file-lines": faFileLines,
  "file-medical": faFileMedical,
  "file-pdf": faFilePdf,
  "file-pen": faFilePen,
  "file-powerpoint": faFilePowerpoint,
  "file-prescription": faFilePrescription,
  "file-shield": faFileShield,
  "file-signature": faFileSignature,
  "file-video": faFileVideo,
  "file-waveform": faFileWaveform,
  "file-word": faFileWord,
  "file-zipper": faFileZipper,
  "fill": faFill,
  "fill-drip": faFillDrip,
  "film": faFilm,
  "filter": faFilter,
  "filter-circle-dollar": faFilterCircleDollar,
  "filter-circle-xmark": faFilterCircleXmark,
  "fingerprint": faFingerprint,
  "fire": faFire,
  "fire-burner": faFireBurner,
  "fire-extinguisher": faFireExtinguisher,
  "fire-flame-curved": faFireFlameCurved,
  "fire-flame-simple": faFireFlameSimple,
  "fish": faFish,
  "fish-fins": faFishFins,
  "flag": faFlag,
  "flag-checkered": faFlagCheckered,
  "flag-usa": faFlagUsa,
  "flask": faFlask,
  "flask-vial": faFlaskVial,
  "florin-sign": faFlorinSign,
  "folder": faFolder,
  "folder-closed": faFolderClosed,
  "folder-minus": faFolderMinus,
  "folder-open": faFolderOpen,
  "folder-plus": faFolderPlus,
  "folder-tree": faFolderTree,
  "font": faFont,
  "font-awesome": faFontAwesome,
  "football": faFootball,
  "forward": faForward,
  "forward-fast": faForwardFast,
  "forward-step": faForwardStep,
  "franc-sign": faFrancSign,
  "frog": faFrog,
  "futbol": faFutbol,
  "g": faG,
  "gamepad": faGamepad,
  "gas-pump": faGasPump,
  "gauge": faGauge,
  "gauge-high": faGaugeHigh,
  "gauge-simple": faGaugeSimple,
  "gauge-simple-high": faGaugeSimpleHigh,
  "gavel": faGavel,
  "gear": faGear,
  "gears": faGears,
  "gem": faGem,
  "gemini": faGemini,
  "genderless": faGenderless,
  "ghost": faGhost,
  "gift": faGift,
  "gifts": faGifts,
  "glass-water": faGlassWater,
  "glass-water-droplet": faGlassWaterDroplet,
  "glasses": faGlasses,
  "globe": faGlobe,
  "golf-ball-tee": faGolfBallTee,
  "gopuram": faGopuram,
  "graduation-cap": faGraduationCap,
  "greater-than": faGreaterThan,
  "greater-than-equal": faGreaterThanEqual,
  "grip": faGrip,
  "grip-lines": faGripLines,
  "grip-lines-vertical": faGripLinesVertical,
  "grip-vertical": faGripVertical,
  "group-arrows-rotate": faGroupArrowsRotate,
  "guarani-sign": faGuaraniSign,
  "guitar": faGuitar,
  "gun": faGun,
  "h": faH,
  "hammer": faHammer,
  "hamsa": faHamsa,
  "hand": faHand,
  "hand-back-fist": faHandBackFist,
  "hand-dots": faHandDots,
  "hand-fist": faHandFist,
  "hand-holding": faHandHolding,
  "hand-holding-dollar": faHandHoldingDollar,
  "hand-holding-droplet": faHandHoldingDroplet,
  "hand-holding-hand": faHandHoldingHand,
  "hand-holding-heart": faHandHoldingHeart,
  "hand-holding-medical": faHandHoldingMedical,
  "hand-lizard": faHandLizard,
  "hand-middle-finger": faHandMiddleFinger,
  "hand-peace": faHandPeace,
  "hand-point-down": faHandPointDown,
  "hand-point-left": faHandPointLeft,
  "hand-point-right": faHandPointRight,
  "hand-point-up": faHandPointUp,
  "hand-pointer": faHandPointer,
  "hand-scissors": faHandScissors,
  "hand-sparkles": faHandSparkles,
  "hand-spock": faHandSpock,
  "handcuffs": faHandcuffs,
  "hands": faHands,
  "hands-asl-interpreting": faHandsAslInterpreting,
  "hands-bound": faHandsBound,
  "hands-bubbles": faHandsBubbles,
  "hands-clapping": faHandsClapping,
  "hands-holding": faHandsHolding,
  "hands-holding-child": faHandsHoldingChild,
  "hands-holding-circle": faHandsHoldingCircle,
  "hands-praying": faHandsPraying,
  "handshake": faHandshake,
  "handshake-angle": faHandshakeAngle,
  "handshake-slash": faHandshakeSlash,
  "hanukiah": faHanukiah,
  "hard-drive": faHardDrive,
  "hashtag": faHashtag,
  "hat-cowboy": faHatCowboy,
  "hat-cowboy-side": faHatCowboySide,
  "hat-wizard": faHatWizard,
  "head-side-cough": faHeadSideCough,
  "head-side-cough-slash": faHeadSideCoughSlash,
  "head-side-mask": faHeadSideMask,
  "head-side-virus": faHeadSideVirus,
  "heading": faHeading,
  "headphones": faHeadphones,
  "headset": faHeadset,
  "heart": faHeart,
  "heart-circle-bolt": faHeartCircleBolt,
  "heart-circle-check": faHeartCircleCheck,
  "heart-circle-exclamation": faHeartCircleExclamation,
  "heart-circle-minus": faHeartCircleMinus,
  "heart-circle-plus": faHeartCirclePlus,
  "heart-circle-xmark": faHeartCircleXmark,
  "heart-crack": faHeartCrack,
  "heart-pulse": faHeartPulse,
  "helicopter": faHelicopter,
  "helicopter-symbol": faHelicopterSymbol,
  "helmet-safety": faHelmetSafety,
  "helmet-un": faHelmetUn,
  "hexagon": faHexagon,
  "hexagon-nodes": faHexagonNodes,
  "hexagon-nodes-bolt": faHexagonNodesBolt,
  "highlighter": faHighlighter,
  "hill-avalanche": faHillAvalanche,
  "hill-rockslide": faHillRockslide,
  "hippo": faHippo,
  "hockey-puck": faHockeyPuck,
  "holly-berry": faHollyBerry,
  "horse": faHorse,
  "horse-head": faHorseHead,
  "hospital": faHospital,
  "hospital-user": faHospitalUser,
  "hot-tub-person": faHotTubPerson,
  "hotdog": faHotdog,
  "hotel": faHotel,
  "hourglass": faHourglass,
  "hourglass-end": faHourglassEnd,
  "hourglass-half": faHourglassHalf,
  "hourglass-start": faHourglassStart,
  "house": faHouse,
  "house-chimney": faHouseChimney,
  "house-chimney-crack": faHouseChimneyCrack,
  "house-chimney-medical": faHouseChimneyMedical,
  "house-chimney-user": faHouseChimneyUser,
  "house-chimney-window": faHouseChimneyWindow,
  "house-circle-check": faHouseCircleCheck,
  "house-circle-exclamation": faHouseCircleExclamation,
  "house-circle-xmark": faHouseCircleXmark,
  "house-crack": faHouseCrack,
  "house-fire": faHouseFire,
  "house-flag": faHouseFlag,
  "house-flood-water": faHouseFloodWater,
  "house-flood-water-circle-arrow-right": faHouseFloodWaterCircleArrowRight,
  "house-laptop": faHouseLaptop,
  "house-lock": faHouseLock,
  "house-medical": faHouseMedical,
  "house-medical-circle-check": faHouseMedicalCircleCheck,
  "house-medical-circle-exclamation": faHouseMedicalCircleExclamation,
  "house-medical-circle-xmark": faHouseMedicalCircleXmark,
  "house-medical-flag": faHouseMedicalFlag,
  "house-signal": faHouseSignal,
  "house-tsunami": faHouseTsunami,
  "house-user": faHouseUser,
  "hryvnia-sign": faHryvniaSign,
  "hurricane": faHurricane,
  "i": faI,
  "i-cursor": faICursor,
  "ice-cream": faIceCream,
  "icicles": faIcicles,
  "icons": faIcons,
  "id-badge": faIdBadge,
  "id-card": faIdCard,
  "id-card-clip": faIdCardClip,
  "igloo": faIgloo,
  "image": faImage,
  "image-portrait": faImagePortrait,
  "images": faImages,
  "inbox": faInbox,
  "indent": faIndent,
  "indian-rupee-sign": faIndianRupeeSign,
  "industry": faIndustry,
  "infinity": faInfinity,
  "info": faInfo,
  "italic": faItalic,
  "j": faJ,
  "jar": faJar,
  "jar-wheat": faJarWheat,
  "jedi": faJedi,
  "jet-fighter": faJetFighter,
  "jet-fighter-up": faJetFighterUp,
  "joint": faJoint,
  "jug-detergent": faJugDetergent,
  "k": faK,
  "kaaba": faKaaba,
  "key": faKey,
  "keyboard": faKeyboard,
  "khanda": faKhanda,
  "kip-sign": faKipSign,
  "kit-medical": faKitMedical,
  "kitchen-set": faKitchenSet,
  "kiwi-bird": faKiwiBird,
  "l": faL,
  "land-mine-on": faLandMineOn,
  "landmark": faLandmark,
  "landmark-dome": faLandmarkDome,
  "landmark-flag": faLandmarkFlag,
  "language": faLanguage,
  "laptop": faLaptop,
  "laptop-code": faLaptopCode,
  "laptop-file": faLaptopFile,
  "laptop-medical": faLaptopMedical,
  "lari-sign": faLariSign,
  "layer-group": faLayerGroup,
  "leaf": faLeaf,
  "left-long": faLeftLong,
  "left-right": faLeftRight,
  "lemon": faLemon,
  "leo": faLeo,
  "less-than": faLessThan,
  "less-than-equal": faLessThanEqual,
  "libra": faLibra,
  "life-ring": faLifeRing,
  "lightbulb": faLightbulb,
  "lines-leaning": faLinesLeaning,
  "link": faLink,
  "link-slash": faLinkSlash,
  "lira-sign": faLiraSign,
  "list": faList,
  "list-check": faListCheck,
  "list-ol": faListOl,
  "list-ul": faListUl,
  "litecoin-sign": faLitecoinSign,
  "location-arrow": faLocationArrow,
  "location-crosshairs": faLocationCrosshairs,
  "location-dot": faLocationDot,
  "location-pin": faLocationPin,
  "location-pin-lock": faLocationPinLock,
  "lock": faLock,
  "lock-open": faLockOpen,
  "locust": faLocust,
  "lungs": faLungs,
  "lungs-virus": faLungsVirus,
  "m": faM,
  "magnet": faMagnet,
  "magnifying-glass": faMagnifyingGlass,
  "magnifying-glass-arrow-right": faMagnifyingGlassArrowRight,
  "magnifying-glass-chart": faMagnifyingGlassChart,
  "magnifying-glass-dollar": faMagnifyingGlassDollar,
  "magnifying-glass-location": faMagnifyingGlassLocation,
  "magnifying-glass-minus": faMagnifyingGlassMinus,
  "magnifying-glass-plus": faMagnifyingGlassPlus,
  "manat-sign": faManatSign,
  "map": faMap,
  "map-location": faMapLocation,
  "map-location-dot": faMapLocationDot,
  "map-pin": faMapPin,
  "marker": faMarker,
  "mars": faMars,
  "mars-and-venus": faMarsAndVenus,
  "mars-and-venus-burst": faMarsAndVenusBurst,
  "mars-double": faMarsDouble,
  "mars-stroke": faMarsStroke,
  "mars-stroke-right": faMarsStrokeRight,
  "mars-stroke-up": faMarsStrokeUp,
  "martini-glass": faMartiniGlass,
  "martini-glass-citrus": faMartiniGlassCitrus,
  "martini-glass-empty": faMartiniGlassEmpty,
  "mask": faMask,
  "mask-face": faMaskFace,
  "mask-ventilator": faMaskVentilator,
  "masks-theater": faMasksTheater,
  "mattress-pillow": faMattressPillow,
  "maximize": faMaximize,
  "medal": faMedal,
  "memory": faMemory,
  "menorah": faMenorah,
  "mercury": faMercury,
  "message": faMessage,
  "meteor": faMeteor,
  "microchip": faMicrochip,
  "microphone": faMicrophone,
  "microphone-lines": faMicrophoneLines,
  "microphone-lines-slash": faMicrophoneLinesSlash,
  "microphone-slash": faMicrophoneSlash,
  "microscope": faMicroscope,
  "mill-sign": faMillSign,
  "minimize": faMinimize,
  "minus": faMinus,
  "mitten": faMitten,
  "mobile": faMobile,
  "mobile-button": faMobileButton,
  "mobile-retro": faMobileRetro,
  "mobile-screen": faMobileScreen,
  "mobile-screen-button": faMobileScreenButton,
  "mobile-vibrate": faMobileVibrate,
  "money-bill": faMoneyBill,
  "money-bill-1": faMoneyBill1,
  "money-bill-1-wave": faMoneyBill1Wave,
  "money-bill-transfer": faMoneyBillTransfer,
  "money-bill-trend-up": faMoneyBillTrendUp,
  "money-bill-wave": faMoneyBillWave,
  "money-bill-wheat": faMoneyBillWheat,
  "money-bills": faMoneyBills,
  "money-check": faMoneyCheck,
  "money-check-dollar": faMoneyCheckDollar,
  "monument": faMonument,
  "moon": faMoon,
  "mortar-pestle": faMortarPestle,
  "mosque": faMosque,
  "mosquito": faMosquito,
  "mosquito-net": faMosquitoNet,
  "motorcycle": faMotorcycle,
  "mound": faMound,
  "mountain": faMountain,
  "mountain-city": faMountainCity,
  "mountain-sun": faMountainSun,
  "mug-hot": faMugHot,
  "mug-saucer": faMugSaucer,
  "music": faMusic,
  "n": faN,
  "naira-sign": faNairaSign,
  "network-wired": faNetworkWired,
  "neuter": faNeuter,
  "newspaper": faNewspaper,
  "non-binary": faNonBinary,
  "not-equal": faNotEqual,
  "notdef": faNotdef,
  "note-sticky": faNoteSticky,
  "notes-medical": faNotesMedical,
  "o": faO,
  "object-group": faObjectGroup,
  "object-ungroup": faObjectUngroup,
  "octagon": faOctagon,
  "oil-can": faOilCan,
  "oil-well": faOilWell,
  "om": faOm,
  "otter": faOtter,
  "outdent": faOutdent,
  "p": faP,
  "pager": faPager,
  "paint-roller": faPaintRoller,
  "paintbrush": faPaintbrush,
  "palette": faPalette,
  "pallet": faPallet,
  "panorama": faPanorama,
  "paper-plane": faPaperPlane,
  "paperclip": faPaperclip,
  "parachute-box": faParachuteBox,
  "paragraph": faParagraph,
  "passport": faPassport,
  "paste": faPaste,
  "pause": faPause,
  "paw": faPaw,
  "peace": faPeace,
  "pen": faPen,
  "pen-clip": faPenClip,
  "pen-fancy": faPenFancy,
  "pen-nib": faPenNib,
  "pen-ruler": faPenRuler,
  "pen-to-square": faPenToSquare,
  "pencil": faPencil,
  "pentagon": faPentagon,
  "people-arrows": faPeopleArrows,
  "people-carry-box": faPeopleCarryBox,
  "people-group": faPeopleGroup,
  "people-line": faPeopleLine,
  "people-pulling": faPeoplePulling,
  "people-robbery": faPeopleRobbery,
  "people-roof": faPeopleRoof,
  "pepper-hot": faPepperHot,
  "percent": faPercent,
  "person": faPerson,
  "person-arrow-down-to-line": faPersonArrowDownToLine,
  "person-arrow-up-from-line": faPersonArrowUpFromLine,
  "person-biking": faPersonBiking,
  "person-booth": faPersonBooth,
  "person-breastfeeding": faPersonBreastfeeding,
  "person-burst": faPersonBurst,
  "person-cane": faPersonCane,
  "person-chalkboard": faPersonChalkboard,
  "person-circle-check": faPersonCircleCheck,
  "person-circle-exclamation": faPersonCircleExclamation,
  "person-circle-minus": faPersonCircleMinus,
  "person-circle-plus": faPersonCirclePlus,
  "person-circle-question": faPersonCircleQuestion,
  "person-circle-xmark": faPersonCircleXmark,
  "person-digging": faPersonDigging,
  "person-dots-from-line": faPersonDotsFromLine,
  "person-dress": faPersonDress,
  "person-dress-burst": faPersonDressBurst,
  "person-drowning": faPersonDrowning,
  "person-falling": faPersonFalling,
  "person-falling-burst": faPersonFallingBurst,
  "person-half-dress": faPersonHalfDress,
  "person-harassing": faPersonHarassing,
  "person-hiking": faPersonHiking,
  "person-military-pointing": faPersonMilitaryPointing,
  "person-military-rifle": faPersonMilitaryRifle,
  "person-military-to-person": faPersonMilitaryToPerson,
  "person-praying": faPersonPraying,
  "person-pregnant": faPersonPregnant,
  "person-rays": faPersonRays,
  "person-rifle": faPersonRifle,
  "person-running": faPersonRunning,
  "person-shelter": faPersonShelter,
  "person-skating": faPersonSkating,
  "person-skiing": faPersonSkiing,
  "person-skiing-nordic": faPersonSkiingNordic,
  "person-snowboarding": faPersonSnowboarding,
  "person-swimming": faPersonSwimming,
  "person-through-window": faPersonThroughWindow,
  "person-walking": faPersonWalking,
  "person-walking-arrow-loop-left": faPersonWalkingArrowLoopLeft,
  "person-walking-arrow-right": faPersonWalkingArrowRight,
  "person-walking-dashed-line-arrow-right": faPersonWalkingDashedLineArrowRight,
  "person-walking-luggage": faPersonWalkingLuggage,
  "person-walking-with-cane": faPersonWalkingWithCane,
  "peseta-sign": faPesetaSign,
  "peso-sign": faPesoSign,
  "phone": faPhone,
  "phone-flip": faPhoneFlip,
  "phone-slash": faPhoneSlash,
  "phone-volume": faPhoneVolume,
  "photo-film": faPhotoFilm,
  "picture-in-picture": faPictureInPicture,
  "piggy-bank": faPiggyBank,
  "pills": faPills,
  "pisces": faPisces,
  "pizza-slice": faPizzaSlice,
  "place-of-worship": faPlaceOfWorship,
  "plane": faPlane,
  "plane-arrival": faPlaneArrival,
  "plane-circle-check": faPlaneCircleCheck,
  "plane-circle-exclamation": faPlaneCircleExclamation,
  "plane-circle-xmark": faPlaneCircleXmark,
  "plane-departure": faPlaneDeparture,
  "plane-lock": faPlaneLock,
  "plane-slash": faPlaneSlash,
  "plane-up": faPlaneUp,
  "plant-wilt": faPlantWilt,
  "plate-wheat": faPlateWheat,
  "play": faPlay,
  "plug": faPlug,
  "plug-circle-bolt": faPlugCircleBolt,
  "plug-circle-check": faPlugCircleCheck,
  "plug-circle-exclamation": faPlugCircleExclamation,
  "plug-circle-minus": faPlugCircleMinus,
  "plug-circle-plus": faPlugCirclePlus,
  "plug-circle-xmark": faPlugCircleXmark,
  "plus": faPlus,
  "plus-minus": faPlusMinus,
  "podcast": faPodcast,
  "poo": faPoo,
  "poo-storm": faPooStorm,
  "poop": faPoop,
  "power-off": faPowerOff,
  "prescription": faPrescription,
  "prescription-bottle": faPrescriptionBottle,
  "prescription-bottle-medical": faPrescriptionBottleMedical,
  "print": faPrint,
  "pump-medical": faPumpMedical,
  "pump-soap": faPumpSoap,
  "puzzle-piece": faPuzzlePiece,
  "q": faQ,
  "qrcode": faQrcode,
  "question": faQuestion,
  "quote-left": faQuoteLeft,
  "quote-right": faQuoteRight,
  "r": faR,
  "radiation": faRadiation,
  "radio": faRadio,
  "rainbow": faRainbow,
  "ranking-star": faRankingStar,
  "receipt": faReceipt,
  "record-vinyl": faRecordVinyl,
  "rectangle-ad": faRectangleAd,
  "rectangle-list": faRectangleList,
  "rectangle-xmark": faRectangleXmark,
  "recycle": faRecycle,
  "registered": faRegistered,
  "repeat": faRepeat,
  "reply": faReply,
  "reply-all": faReplyAll,
  "republican": faRepublican,
  "restroom": faRestroom,
  "retweet": faRetweet,
  "ribbon": faRibbon,
  "right-from-bracket": faRightFromBracket,
  "right-left": faRightLeft,
  "right-long": faRightLong,
  "right-to-bracket": faRightToBracket,
  "ring": faRing,
  "road": faRoad,
  "road-barrier": faRoadBarrier,
  "road-bridge": faRoadBridge,
  "road-circle-check": faRoadCircleCheck,
  "road-circle-exclamation": faRoadCircleExclamation,
  "road-circle-xmark": faRoadCircleXmark,
  "road-lock": faRoadLock,
  "road-spikes": faRoadSpikes,
  "robot": faRobot,
  "rocket": faRocket,
  "rotate": faRotate,
  "rotate-left": faRotateLeft,
  "rotate-right": faRotateRight,
  "route": faRoute,
  "rss": faRss,
  "ruble-sign": faRubleSign,
  "rug": faRug,
  "ruler": faRuler,
  "ruler-combined": faRulerCombined,
  "ruler-horizontal": faRulerHorizontal,
  "ruler-vertical": faRulerVertical,
  "rupee-sign": faRupeeSign,
  "rupiah-sign": faRupiahSign,
  "s": faS,
  "sack-dollar": faSackDollar,
  "sack-xmark": faSackXmark,
  "sagittarius": faSagittarius,
  "sailboat": faSailboat,
  "satellite": faSatellite,
  "satellite-dish": faSatelliteDish,
  "scale-balanced": faScaleBalanced,
  "scale-unbalanced": faScaleUnbalanced,
  "scale-unbalanced-flip": faScaleUnbalancedFlip,
  "school": faSchool,
  "school-circle-check": faSchoolCircleCheck,
  "school-circle-exclamation": faSchoolCircleExclamation,
  "school-circle-xmark": faSchoolCircleXmark,
  "school-flag": faSchoolFlag,
  "school-lock": faSchoolLock,
  "scissors": faScissors,
  "scorpio": faScorpio,
  "screwdriver": faScrewdriver,
  "screwdriver-wrench": faScrewdriverWrench,
  "scroll": faScroll,
  "scroll-torah": faScrollTorah,
  "sd-card": faSdCard,
  "section": faSection,
  "seedling": faSeedling,
  "septagon": faSeptagon,
  "server": faServer,
  "shapes": faShapes,
  "share": faShare,
  "share-from-square": faShareFromSquare,
  "share-nodes": faShareNodes,
  "sheet-plastic": faSheetPlastic,
  "shekel-sign": faShekelSign,
  "shield": faShield,
  "shield-cat": faShieldCat,
  "shield-dog": faShieldDog,
  "shield-halved": faShieldHalved,
  "shield-heart": faShieldHeart,
  "shield-virus": faShieldVirus,
  "ship": faShip,
  "shirt": faShirt,
  "shoe-prints": faShoePrints,
  "shop": faShop,
  "shop-lock": faShopLock,
  "shop-slash": faShopSlash,
  "shower": faShower,
  "shrimp": faShrimp,
  "shuffle": faShuffle,
  "shuttle-space": faShuttleSpace,
  "sign-hanging": faSignHanging,
  "signal": faSignal,
  "signature": faSignature,
  "signs-post": faSignsPost,
  "sim-card": faSimCard,
  "single-quote-left": faSingleQuoteLeft,
  "single-quote-right": faSingleQuoteRight,
  "sink": faSink,
  "sitemap": faSitemap,
  "skull": faSkull,
  "skull-crossbones": faSkullCrossbones,
  "slash": faSlash,
  "sleigh": faSleigh,
  "sliders": faSliders,
  "smog": faSmog,
  "smoking": faSmoking,
  "snowflake": faSnowflake,
  "snowman": faSnowman,
  "snowplow": faSnowplow,
  "soap": faSoap,
  "socks": faSocks,
  "solar-panel": faSolarPanel,
  "sort": faSort,
  "sort-down": faSortDown,
  "sort-up": faSortUp,
  "spa": faSpa,
  "spaghetti-monster-flying": faSpaghettiMonsterFlying,
  "spell-check": faSpellCheck,
  "spider": faSpider,
  "spinner": faSpinner,
  "spiral": faSpiral,
  "splotch": faSplotch,
  "spoon": faSpoon,
  "spray-can": faSprayCan,
  "spray-can-sparkles": faSprayCanSparkles,
  "square": faSquare,
  "square-arrow-up-right": faSquareArrowUpRight,
  "square-binary": faSquareBinary,
  "square-caret-down": faSquareCaretDown,
  "square-caret-left": faSquareCaretLeft,
  "square-caret-right": faSquareCaretRight,
  "square-caret-up": faSquareCaretUp,
  "square-check": faSquareCheck,
  "square-envelope": faSquareEnvelope,
  "square-full": faSquareFull,
  "square-h": faSquareH,
  "square-minus": faSquareMinus,
  "square-nfi": faSquareNfi,
  "square-parking": faSquareParking,
  "square-pen": faSquarePen,
  "square-person-confined": faSquarePersonConfined,
  "square-phone": faSquarePhone,
  "square-phone-flip": faSquarePhoneFlip,
  "square-plus": faSquarePlus,
  "square-poll-horizontal": faSquarePollHorizontal,
  "square-poll-vertical": faSquarePollVertical,
  "square-root-variable": faSquareRootVariable,
  "square-rss": faSquareRss,
  "square-share-nodes": faSquareShareNodes,
  "square-up-right": faSquareUpRight,
  "square-virus": faSquareVirus,
  "square-xmark": faSquareXmark,
  "staff-snake": faStaffSnake,
  "stairs": faStairs,
  "stamp": faStamp,
  "stapler": faStapler,
  "star": faStar,
  "star-and-crescent": faStarAndCrescent,
  "star-half": faStarHalf,
  "star-half-stroke": faStarHalfStroke,
  "star-of-david": faStarOfDavid,
  "star-of-life": faStarOfLife,
  "sterling-sign": faSterlingSign,
  "stethoscope": faStethoscope,
  "stop": faStop,
  "stopwatch": faStopwatch,
  "stopwatch-20": faStopwatch20,
  "store": faStore,
  "store-slash": faStoreSlash,
  "street-view": faStreetView,
  "strikethrough": faStrikethrough,
  "stroopwafel": faStroopwafel,
  "subscript": faSubscript,
  "suitcase": faSuitcase,
  "suitcase-medical": faSuitcaseMedical,
  "suitcase-rolling": faSuitcaseRolling,
  "sun": faSun,
  "sun-plant-wilt": faSunPlantWilt,
  "superscript": faSuperscript,
  "swatchbook": faSwatchbook,
  "synagogue": faSynagogue,
  "syringe": faSyringe,
  "t": faT,
  "table": faTable,
  "table-cells": faTableCells,
  "table-cells-column-lock": faTableCellsColumnLock,
  "table-cells-large": faTableCellsLarge,
  "table-cells-row-lock": faTableCellsRowLock,
  "table-cells-row-unlock": faTableCellsRowUnlock,
  "table-columns": faTableColumns,
  "table-list": faTableList,
  "table-tennis-paddle-ball": faTableTennisPaddleBall,
  "tablet": faTablet,
  "tablet-button": faTabletButton,
  "tablet-screen-button": faTabletScreenButton,
  "tablets": faTablets,
  "tachograph-digital": faTachographDigital,
  "tag": faTag,
  "tags": faTags,
  "tape": faTape,
  "tarp": faTarp,
  "tarp-droplet": faTarpDroplet,
  "taurus": faTaurus,
  "taxi": faTaxi,
  "teeth": faTeeth,
  "teeth-open": faTeethOpen,
  "temperature-arrow-down": faTemperatureArrowDown,
  "temperature-arrow-up": faTemperatureArrowUp,
  "temperature-empty": faTemperatureEmpty,
  "temperature-full": faTemperatureFull,
  "temperature-half": faTemperatureHalf,
  "temperature-high": faTemperatureHigh,
  "temperature-low": faTemperatureLow,
  "temperature-quarter": faTemperatureQuarter,
  "temperature-three-quarters": faTemperatureThreeQuarters,
  "tenge-sign": faTengeSign,
  "tent": faTent,
  "tent-arrow-down-to-line": faTentArrowDownToLine,
  "tent-arrow-left-right": faTentArrowLeftRight,
  "tent-arrow-turn-left": faTentArrowTurnLeft,
  "tent-arrows-down": faTentArrowsDown,
  "tents": faTents,
  "terminal": faTerminal,
  "text-height": faTextHeight,
  "text-slash": faTextSlash,
  "text-width": faTextWidth,
  "thermometer": faThermometer,
  "thumbs-down": faThumbsDown,
  "thumbs-up": faThumbsUp,
  "thumbtack": faThumbtack,
  "thumbtack-slash": faThumbtackSlash,
  "ticket": faTicket,
  "ticket-simple": faTicketSimple,
  "timeline": faTimeline,
  "toggle-off": faToggleOff,
  "toggle-on": faToggleOn,
  "toilet": faToilet,
  "toilet-paper": faToiletPaper,
  "toilet-paper-slash": faToiletPaperSlash,
  "toilet-portable": faToiletPortable,
  "toilets-portable": faToiletsPortable,
  "toolbox": faToolbox,
  "tooth": faTooth,
  "torii-gate": faToriiGate,
  "tornado": faTornado,
  "tower-broadcast": faTowerBroadcast,
  "tower-cell": faTowerCell,
  "tower-observation": faTowerObservation,
  "tractor": faTractor,
  "trademark": faTrademark,
  "traffic-light": faTrafficLight,
  "trailer": faTrailer,
  "train": faTrain,
  "train-subway": faTrainSubway,
  "train-tram": faTrainTram,
  "transgender": faTransgender,
  "trash": faTrash,
  "trash-arrow-up": faTrashArrowUp,
  "trash-can": faTrashCan,
  "trash-can-arrow-up": faTrashCanArrowUp,
  "tree": faTree,
  "tree-city": faTreeCity,
  "triangle-exclamation": faTriangleExclamation,
  "trophy": faTrophy,
  "trowel": faTrowel,
  "trowel-bricks": faTrowelBricks,
  "truck": faTruck,
  "truck-arrow-right": faTruckArrowRight,
  "truck-droplet": faTruckDroplet,
  "truck-fast": faTruckFast,
  "truck-field": faTruckField,
  "truck-field-un": faTruckFieldUn,
  "truck-front": faTruckFront,
  "truck-medical": faTruckMedical,
  "truck-monster": faTruckMonster,
  "truck-moving": faTruckMoving,
  "truck-pickup": faTruckPickup,
  "truck-plane": faTruckPlane,
  "truck-ramp-box": faTruckRampBox,
  "tty": faTty,
  "turkish-lira-sign": faTurkishLiraSign,
  "turn-down": faTurnDown,
  "turn-up": faTurnUp,
  "tv": faTv,
  "u": faU,
  "umbrella": faUmbrella,
  "umbrella-beach": faUmbrellaBeach,
  "underline": faUnderline,
  "universal-access": faUniversalAccess,
  "unlock": faUnlock,
  "unlock-keyhole": faUnlockKeyhole,
  "up-down": faUpDown,
  "up-down-left-right": faUpDownLeftRight,
  "up-long": faUpLong,
  "up-right-and-down-left-from-center": faUpRightAndDownLeftFromCenter,
  "up-right-from-square": faUpRightFromSquare,
  "upload": faUpload,
  "user": faUser,
  "user-astronaut": faUserAstronaut,
  "user-check": faUserCheck,
  "user-clock": faUserClock,
  "user-doctor": faUserDoctor,
  "user-gear": faUserGear,
  "user-graduate": faUserGraduate,
  "user-group": faUserGroup,
  "user-injured": faUserInjured,
  "user-lock": faUserLock,
  "user-minus": faUserMinus,
  "user-ninja": faUserNinja,
  "user-nurse": faUserNurse,
  "user-pen": faUserPen,
  "user-plus": faUserPlus,
  "user-secret": faUserSecret,
  "user-shield": faUserShield,
  "user-slash": faUserSlash,
  "user-tag": faUserTag,
  "user-tie": faUserTie,
  "user-xmark": faUserXmark,
  "users": faUsers,
  "users-between-lines": faUsersBetweenLines,
  "users-gear": faUsersGear,
  "users-line": faUsersLine,
  "users-rays": faUsersRays,
  "users-rectangle": faUsersRectangle,
  "users-slash": faUsersSlash,
  "users-viewfinder": faUsersViewfinder,
  "utensils": faUtensils,
  "v": faV,
  "van-shuttle": faVanShuttle,
  "vault": faVault,
  "venus": faVenus,
  "venus-double": faVenusDouble,
  "venus-mars": faVenusMars,
  "vest": faVest,
  "vest-patches": faVestPatches,
  "vial": faVial,
  "vial-circle-check": faVialCircleCheck,
  "vial-virus": faVialVirus,
  "vials": faVials,
  "video": faVideo,
  "video-slash": faVideoSlash,
  "vihara": faVihara,
  "virgo": faVirgo,
  "virus": faVirus,
  "virus-covid": faVirusCovid,
  "virus-covid-slash": faVirusCovidSlash,
  "virus-slash": faVirusSlash,
  "viruses": faViruses,
  "voicemail": faVoicemail,
  "volcano": faVolcano,
  "volleyball": faVolleyball,
  "volume": faVolume,
  "volume-high": faVolumeHigh,
  "volume-low": faVolumeLow,
  "volume-off": faVolumeOff,
  "volume-xmark": faVolumeXmark,
  "vr-cardboard": faVrCardboard,
  "w": faW,
  "walkie-talkie": faWalkieTalkie,
  "wallet": faWallet,
  "wand-magic": faWandMagic,
  "wand-magic-sparkles": faWandMagicSparkles,
  "wand-sparkles": faWandSparkles,
  "warehouse": faWarehouse,
  "water": faWater,
  "water-ladder": faWaterLadder,
  "wave-square": faWaveSquare,
  "web-awesome": faWebAwesome,
  "weight-hanging": faWeightHanging,
  "weight-scale": faWeightScale,
  "wheat-awn": faWheatAwn,
  "wheat-awn-circle-exclamation": faWheatAwnCircleExclamation,
  "wheelchair": faWheelchair,
  "wheelchair-move": faWheelchairMove,
  "whiskey-glass": faWhiskeyGlass,
  "wifi": faWifi,
  "wind": faWind,
  "window-maximize": faWindowMaximize,
  "window-minimize": faWindowMinimize,
  "window-restore": faWindowRestore,
  "wine-bottle": faWineBottle,
  "wine-glass": faWineGlass,
  "wine-glass-empty": faWineGlassEmpty,
  "won-sign": faWonSign,
  "worm": faWorm,
  "wrench": faWrench,
  "x": faX,
  "x-ray": faXRay,
  "xmark": faXmark,
  "xmarks-lines": faXmarksLines,
  "y": faY,
  "yen-sign": faYenSign,
  "yin-yang": faYinYang,
  "z": faZ,

  // ─────────────────────────────────────────────────────────
  // Legacy bare keys pinned to the REGULAR (outline) style —
  // preserved exactly as the original hand-written file had them,
  // so no existing icon reference in the app changes appearance.
  // ─────────────────────────────────────────────────────────
  "eye": faEyeOutline,
  "eye-slash": faEyeSlashOutline,
  "floppy-disk": faFloppyDiskOutline,
  "circle-check": faCircleCheckOutline,
  "circle-xmark": faCircleXmarkOutline,

  // ─────────────────────────────────────────────────────────
  // Regular icons (outline style) — suffixed "-outline" so they
  // never collide with the solid/default versions above.
  // Use these when a lighter/outline visual weight is wanted.
  // ─────────────────────────────────────────────────────────
  "address-book-outline": faAddressBookOutline,
  "address-card-outline": faAddressCardOutline,
  "alarm-clock-outline": faAlarmClockOutline,
  "bell-outline": faBellOutline,
  "bell-slash-outline": faBellSlashOutline,
  "bookmark-outline": faBookmarkOutline,
  "building-outline": faBuildingOutline,
  "calendar-outline": faCalendarOutline,
  "calendar-check-outline": faCalendarCheckOutline,
  "calendar-days-outline": faCalendarDaysOutline,
  "calendar-minus-outline": faCalendarMinusOutline,
  "calendar-plus-outline": faCalendarPlusOutline,
  "calendar-xmark-outline": faCalendarXmarkOutline,
  "camera-outline": faCameraOutline,
  "chart-bar-outline": faChartBarOutline,
  "chess-bishop-outline": faChessBishopOutline,
  "chess-king-outline": faChessKingOutline,
  "chess-knight-outline": faChessKnightOutline,
  "chess-pawn-outline": faChessPawnOutline,
  "chess-queen-outline": faChessQueenOutline,
  "chess-rook-outline": faChessRookOutline,
  "circle-outline": faCircleOutline,
  "circle-check-outline": faCircleCheckOutline,
  "circle-dot-outline": faCircleDotOutline,
  "circle-down-outline": faCircleDownOutline,
  "circle-left-outline": faCircleLeftOutline,
  "circle-pause-outline": faCirclePauseOutline,
  "circle-play-outline": faCirclePlayOutline,
  "circle-question-outline": faCircleQuestionOutline,
  "circle-right-outline": faCircleRightOutline,
  "circle-stop-outline": faCircleStopOutline,
  "circle-up-outline": faCircleUpOutline,
  "circle-user-outline": faCircleUserOutline,
  "circle-xmark-outline": faCircleXmarkOutline,
  "clipboard-outline": faClipboardOutline,
  "clock-outline": faClockOutline,
  "clone-outline": faCloneOutline,
  "closed-captioning-outline": faClosedCaptioningOutline,
  "cloud-outline": faCloudOutline,
  "comment-outline": faCommentOutline,
  "comment-dots-outline": faCommentDotsOutline,
  "comments-outline": faCommentsOutline,
  "compass-outline": faCompassOutline,
  "copy-outline": faCopyOutline,
  "copyright-outline": faCopyrightOutline,
  "credit-card-outline": faCreditCardOutline,
  "envelope-outline": faEnvelopeOutline,
  "envelope-open-outline": faEnvelopeOpenOutline,
  "eye-outline": faEyeOutline,
  "eye-slash-outline": faEyeSlashOutline,
  "face-angry-outline": faFaceAngryOutline,
  "face-dizzy-outline": faFaceDizzyOutline,
  "face-flushed-outline": faFaceFlushedOutline,
  "face-frown-outline": faFaceFrownOutline,
  "face-frown-open-outline": faFaceFrownOpenOutline,
  "face-grimace-outline": faFaceGrimaceOutline,
  "face-grin-outline": faFaceGrinOutline,
  "face-grin-beam-outline": faFaceGrinBeamOutline,
  "face-grin-beam-sweat-outline": faFaceGrinBeamSweatOutline,
  "face-grin-hearts-outline": faFaceGrinHeartsOutline,
  "face-grin-squint-outline": faFaceGrinSquintOutline,
  "face-grin-squint-tears-outline": faFaceGrinSquintTearsOutline,
  "face-grin-stars-outline": faFaceGrinStarsOutline,
  "face-grin-tears-outline": faFaceGrinTearsOutline,
  "face-grin-tongue-outline": faFaceGrinTongueOutline,
  "face-grin-tongue-squint-outline": faFaceGrinTongueSquintOutline,
  "face-grin-tongue-wink-outline": faFaceGrinTongueWinkOutline,
  "face-grin-wide-outline": faFaceGrinWideOutline,
  "face-grin-wink-outline": faFaceGrinWinkOutline,
  "face-kiss-outline": faFaceKissOutline,
  "face-kiss-beam-outline": faFaceKissBeamOutline,
  "face-kiss-wink-heart-outline": faFaceKissWinkHeartOutline,
  "face-laugh-outline": faFaceLaughOutline,
  "face-laugh-beam-outline": faFaceLaughBeamOutline,
  "face-laugh-squint-outline": faFaceLaughSquintOutline,
  "face-laugh-wink-outline": faFaceLaughWinkOutline,
  "face-meh-outline": faFaceMehOutline,
  "face-meh-blank-outline": faFaceMehBlankOutline,
  "face-rolling-eyes-outline": faFaceRollingEyesOutline,
  "face-sad-cry-outline": faFaceSadCryOutline,
  "face-sad-tear-outline": faFaceSadTearOutline,
  "face-smile-outline": faFaceSmileOutline,
  "face-smile-beam-outline": faFaceSmileBeamOutline,
  "face-smile-wink-outline": faFaceSmileWinkOutline,
  "face-surprise-outline": faFaceSurpriseOutline,
  "face-tired-outline": faFaceTiredOutline,
  "file-outline": faFileOutline,
  "file-audio-outline": faFileAudioOutline,
  "file-code-outline": faFileCodeOutline,
  "file-excel-outline": faFileExcelOutline,
  "file-image-outline": faFileImageOutline,
  "file-lines-outline": faFileLinesOutline,
  "file-pdf-outline": faFilePdfOutline,
  "file-powerpoint-outline": faFilePowerpointOutline,
  "file-video-outline": faFileVideoOutline,
  "file-word-outline": faFileWordOutline,
  "file-zipper-outline": faFileZipperOutline,
  "flag-outline": faFlagOutline,
  "floppy-disk-outline": faFloppyDiskOutline,
  "folder-outline": faFolderOutline,
  "folder-closed-outline": faFolderClosedOutline,
  "folder-open-outline": faFolderOpenOutline,
  "font-awesome-outline": faFontAwesomeOutline,
  "futbol-outline": faFutbolOutline,
  "gem-outline": faGemOutline,
  "hand-outline": faHandOutline,
  "hand-back-fist-outline": faHandBackFistOutline,
  "hand-lizard-outline": faHandLizardOutline,
  "hand-peace-outline": faHandPeaceOutline,
  "hand-point-down-outline": faHandPointDownOutline,
  "hand-point-left-outline": faHandPointLeftOutline,
  "hand-point-right-outline": faHandPointRightOutline,
  "hand-point-up-outline": faHandPointUpOutline,
  "hand-pointer-outline": faHandPointerOutline,
  "hand-scissors-outline": faHandScissorsOutline,
  "hand-spock-outline": faHandSpockOutline,
  "handshake-outline": faHandshakeOutline,
  "hard-drive-outline": faHardDriveOutline,
  "headphones-outline": faHeadphonesOutline,
  "heart-outline": faHeartOutline,
  "hospital-outline": faHospitalOutline,
  "hourglass-outline": faHourglassOutline,
  "hourglass-half-outline": faHourglassHalfOutline,
  "house-outline": faHouseOutline,
  "id-badge-outline": faIdBadgeOutline,
  "id-card-outline": faIdCardOutline,
  "image-outline": faImageOutline,
  "images-outline": faImagesOutline,
  "keyboard-outline": faKeyboardOutline,
  "lemon-outline": faLemonOutline,
  "life-ring-outline": faLifeRingOutline,
  "lightbulb-outline": faLightbulbOutline,
  "map-outline": faMapOutline,
  "message-outline": faMessageOutline,
  "money-bill-1-outline": faMoneyBill1Outline,
  "moon-outline": faMoonOutline,
  "newspaper-outline": faNewspaperOutline,
  "note-sticky-outline": faNoteStickyOutline,
  "object-group-outline": faObjectGroupOutline,
  "object-ungroup-outline": faObjectUngroupOutline,
  "paper-plane-outline": faPaperPlaneOutline,
  "paste-outline": faPasteOutline,
  "pen-to-square-outline": faPenToSquareOutline,
  "rectangle-list-outline": faRectangleListOutline,
  "rectangle-xmark-outline": faRectangleXmarkOutline,
  "registered-outline": faRegisteredOutline,
  "share-from-square-outline": faShareFromSquareOutline,
  "snowflake-outline": faSnowflakeOutline,
  "square-outline": faSquareOutline,
  "square-caret-down-outline": faSquareCaretDownOutline,
  "square-caret-left-outline": faSquareCaretLeftOutline,
  "square-caret-right-outline": faSquareCaretRightOutline,
  "square-caret-up-outline": faSquareCaretUpOutline,
  "square-check-outline": faSquareCheckOutline,
  "square-full-outline": faSquareFullOutline,
  "square-minus-outline": faSquareMinusOutline,
  "square-plus-outline": faSquarePlusOutline,
  "star-outline": faStarOutline,
  "star-half-outline": faStarHalfOutline,
  "star-half-stroke-outline": faStarHalfStrokeOutline,
  "sun-outline": faSunOutline,
  "thumbs-down-outline": faThumbsDownOutline,
  "thumbs-up-outline": faThumbsUpOutline,
  "trash-can-outline": faTrashCanOutline,
  "truck-outline": faTruckOutline,
  "user-outline": faUserOutline,
  "window-maximize-outline": faWindowMaximizeOutline,
  "window-minimize-outline": faWindowMinimizeOutline,
  "window-restore-outline": faWindowRestoreOutline,
});

/**
 * Resolve a string icon name to a Font Awesome icon definition.
 * Returns `null` when the name is empty or not mapped.
 *
 * @param {string} name  Icon name (e.g. "pen", "trash-outline", "gear").
 * @returns {import("@fortawesome/fontawesome-svg-core").IconDefinition | null}
 */
export function resolveIcon(name) {
  const key = String(name || "").trim();
  if (!key) return null;
  return ICON_MAP[key] || null;
}